- src/addons/board_led.cpp
This makes the LED react to unprocessed input state.
Please verify and merge.
Thanks!
> Fix board LED to account for all inputs with raw input state.

- headers/addons/dualdirectional.h
- headers/storagemanager.h
- src/addons/dualdirectional.cpp
Mixed (Up-Win or Neutral) -
(Gamepad OR Dual) Left + (Gamepad OR Dual) Right = Neutral in Up-Win & Neutral
(Gamepad OR Dual) Up + (Gamepad OR Dual) Down = Up in Up-Win, Neutral in Neutral
Hold (Dual) Right -> Add and Hold (Gamepad) Left -> Add and Hold (Gamepad) Right = Right in Up-Win & Neutral
Hold (Dual) Right -> Add and Hold (Gamepad) Left -> Add and Hold (Gamepad) Right -> Add and Hold (Dual) Left = Neutral in Up-Win & Neutral
Hold (Dual) Down -> Add and Hold (Gamepad) Up -> Add and Hold (Gamepad) Down = Up in Up-Win, Neutral in Neutral
Mixed (Last-Win) -
(Gamepad or Dual) Left -> (Gamepad or Dual) Left + (Gamepad or Dual) Right = Right
Hold (Gamepad) Left -> Add and Hold (Dual) Right -> Add and Hold (Dual) Left -> Add and Hold (Gamepad) Right = Right
> Dual Directional SOCD Fix Issue#24

- headers/addonmanager.h
- lib/AnimationStation/src/Animation.hpp
- src/addonmanager.cpp
- src/addons/neopicoleds.cpp
I fixed compiler warnings that were at least triggered with my build setup (Arm GNU Toolchain 12.2.Rel1 (Build arm-12.24)). In more detail, this is what I did:
- Removed `typedef`s from `addonmanager.h`. These triggered the `'typedef' was ignored in this declaration` warning. `typedef`s are pretty much useless in C++ (as opposed to C) anyway.
- I fixed multiple instances of `warning: control reaches end of non-void function`. I added `assert(false)` where the code path should be unreachable. But at least in the case of `AddonManager::GetAddon()` this was an actual issue. Calling this function with an unknown addon name would cause undefined behaviour.
There are still some compiler warnings left in `httpd.c`.  I did not touch those as this is external code.
Also there are some linker …
> Fixed multiple compiler warnings

- headers/addons/i2cdisplay.h
- src/addons/i2cdisplay.cpp
This fixes the stick animation bug in the `DPAD_MODE_LEFT_ANALOG` and `DPAD_MODE_RIGHT_ANALOG` modes. The code now takes the current D-Pad mode into account when displaying a direction.
One could make the point that the unprocessed input should be displayed instead, but doing this would also disregard SOCD cleaning on the display. This leads to the more fundamental question of whether the display should show the actual input or what is send to the PC / console. I favoured the latter interpretation because I think it is more useful for the user.
> Fixed bug #18

- headers/addons/i2cdisplay.h
- src/addons/i2cdisplay.cpp
This is my attempt at solving #15.
I use the same general strategy as the [FlashFloppy](https://github.com/keirf/flashfloppy/) project for differentiating between SSD1306 and SH1106 displays. SH1106 allows read operations over I2C whereas SSD1306 does not. I do some read-modify-write operations and if I can read back data I previously wrote, I re-initialize the display as SH1106, otherwise I leave it as is.
I tested this with both types of displays and for me this approach works perfectly. Testing with a wider variety of OLEDs would be better, of course. I only own two makes of OLEDs.
I can see the merit of a user-configurable options as well, but I think this is a better default. A manual override option can be added to the web config at any time.
> Auto-detect SH1106 OLED displays

- CMakeLists.txt
- headers/system.h
- src/configs/webconfig.cpp
- src/system.cpp
This is my attempt at implementing #60.
I implemented various memory-diagnostic functions in a new `System` namespace:
- `System::getTotalFlash()` - Returns the size of on-board flash memory
- `System::getUsedFlash()` - Returns the amount of on-board flash memory used by the firmware. This only includes flash memory used by the firmware, not the memory used by `FlashPROM`.
- `System::getStaticAllocs()` - Returns the amount of memory used for static allocations (e.g. static variables, static arrays, the stack for both cores, and code placed into memory for speed purposes)
- `System::getTotalHeap()` - Returns the total amount of memory used for dynamic allocations
- `System::getUsedHeap()` - Returns the amount of dynamically allocated memory
I also implemented an API endpoint for the Web …
> Implemented memory report endpoint

- src/configs/webconfig.cpp
Previously responses to webconfig API requests would not include any HTTP headers, which is not valid HTTP and also makes it difficult to communicate with the webconfig API with standard tools (i.e. [curl](https://curl.se), [Postman](https://www.postman.com)).
This PR fixes this issue by including proper HTTP/1.0 headers in API responses.
> Added HTTP response headers to webconfig API requests

- configs/Pico/BoardConfig.h
This solves an unintentional setting previously updated by mistake in Pico BoardConfig.h.
> Fix slider pins default value

- CMakeLists.txt
- configs/Pico/BoardConfig.h
- headers/storagemanager.h
- src/addons/buzzerspeaker.cpp
- src/configs/webconfig.cpp
- src/gp2040aux.cpp
- src/storagemanager.cpp
This PR enables the previously removed Buzzer addon due to M1 issues.
>  Reenable buzzer addon

- headers/storagemanager.h
- lib/OneBitDisplay/OneBitDisplay.cpp
- lib/OneBitDisplay/OneBitDisplay.h
The following changes address issue: #99
Two new modes have been added with the regular Flip mode.
This should help address issues with screens that have their displays flipped by default.
> Add more display flip modes (for #99)

- src/addons/playernum.cpp
Disconnect USB while we wait for reboot, this should allow the lower player numbers to connect while the uppers are disconnected
> Player Number Fix

- CMakeLists.txt
- lib/FlashPROM/src/FlashPROM.cpp
I removed the multicore lockout workarounds that are no longer needed with Pi Pico SDK 1.5.0. I also updated the required SDK version in `CMakeLists.txt`.
> Removed multicore workarounds not needed with Pico SDK 1.5

- src/gamepad.cpp
This will fix the inversion X and Y axis issue on upgrade
The gamepad storage was not properly setting default values for invert X/Y
Additionally, MPG was updated to place the CRC32 in the correct position
> Fixed inversion X and Y axis on upgrade (0.6.0->0.6.1)

- headers/configs/webconfig.h
- src/configs/webconfig.cpp
This PR adds extra buttons to reboot button prompt to reboot the Pico to the respective modes such as Controller, Web-config and BOOTSEL.
Also requires: https://github.com/OpenStickCommunity/WebConfigurator/pull/27
> Expose additional boot modes

- CMakeLists.txt
- configs/BentoBox/BoardConfig.h
- configs/DURAL/BoardConfig.h
- configs/FightboardV3/BoardConfig.h
- configs/FightboardV3Mirrored/BoardConfig.h
- configs/FlatboxRev4/BoardConfig.h
- configs/FlatboxRev5/BoardConfig.h
- configs/MavercadeKeebfighter/BoardConfig.h
- configs/Pico/BoardConfig.h
- configs/PicoAnn/BoardConfig.h
- configs/PicoFightingBoard/BoardConfig.h
- configs/WaveshareZero/BoardConfig.h
- headers/addons/slider_socd.h
- headers/storagemanager.h
- src/addons/slider_socd.cpp
- src/configs/webconfig.cpp
- src/gp2040.cpp
- src/storagemanager.cpp
This adds a feature that allows changing SOCD with slider input.
It also should close #132 and #133.
> Implement SOCD Slider addon

- .gitmodules
- CMakeLists.txt
- headers/gamepad.h
- headers/gamepad/GamepadConfig.h
- headers/gamepad/GamepadDebouncer.h
- headers/gamepad/GamepadDescriptors.h
- headers/gamepad/GamepadEnums.h
- headers/gamepad/GamepadOptions.h
- headers/gamepad/GamepadState.h
- headers/gamepad/GamepadStorage.h
- headers/gamepad/descriptors/HIDDescriptors.h
- headers/gamepad/descriptors/SwitchDescriptors.h
- headers/gamepad/descriptors/XInputDescriptors.h
- headers/themes.h
- lib/TinyUSB_Gamepad/CMakeLists.txt
- lib/TinyUSB_Gamepad/library.json
- lib/TinyUSB_Gamepad/src/hid_driver.cpp
- lib/TinyUSB_Gamepad/src/hid_driver.h
- lib/TinyUSB_Gamepad/src/tusb_driver.cpp
- lib/TinyUSB_Gamepad/src/usb_descriptors.cpp
- lib/TinyUSB_Gamepad/src/usb_driver.h
- lib/TinyUSB_Gamepad/src/xinput_driver.h
- src/gamepad.cpp
- src/gamepad/GamepadDebouncer.cpp
- src/gamepad/GamepadDescriptors.cpp
This cleans the MPG instance from GP2040-CE, using the same code as MPG had but removing the extra layer.
We still need to clean this code as its pretty messy and has WAY too many inlines and statics, but this is the first step!
> Removing MPG from GP2040-CE

- CMakeLists.txt
- src/addons/turbo.cpp
This fixes one more `(uint8_t)val != -1` bug that wasn't caught before v0.6.3.
I also added a compiler warning flag `-Wtype-limits`, to help prevent this category of bug from recurring in the future. This warning flag emitted one warning with my bugfix commit reverted, and otherwise adds zero new warnings.
- `-Wtype-limits` is my favorite compiler warning not enabled in `-Wall -Wextra`; it's good (not perfect) at catching unsigned int bugs, and has never raised a false positive warning in all my use so far.
I find casting -1 to uint8_t to be ~~quite a messy way~~ of testing a variable for "not present". Alternatives include:
- Leave it as-is, and rely on compiler warnings to catch missing casts.
- replace with `std::optional` (takes up 2 bytes of RAM, might break web configurator?)
- …
> Add compiler warning -Wtype-limits, fix comparison bug

- configs/Pico/BoardConfig.h
- configs/PicoAnn/BoardConfig.h
- configs/SparkFunProMicro/BoardConfig.h
- configs/WaveshareZero/BoardConfig.h
This PR disables Turbo by default in the following configs:
Pico
PicoAnn
SparkFunProMicro
WaveshareZero
> Disable turbo by default

- README.md
- docs/_navbar.md
- docs/faq.md
- docs/gp2040-shortcuts.md
Changes made on docs pages:
README.md
- Update Pico pinout link - 
https://github.com/OpenStickCommunity/GP2040-CE/tree/main/configs/Pico/assets/PinMapping.png
- Remove Crush Counter (Configs no longer avalible)
- Update DURAL link
https://github.com/OpenStickCommunity/GP2040-CE/tree/main/configs/DURAL
- Update Flatbox Rev 4 link
https://github.com/OpenStickCommunity/GP2040-CE/tree/main/configs/FlatboxRev4
- Update Flatbox Rev 5 link
https://github.com/OpenStickCommunity/GP2040-CE/tree/main/configs/FlatboxRev5
- Update WaveShare RP2040-Zero link
https://github.com/OpenStickCommunity/GP2040-CE/tree/main/configs/WaveshareZero
- Update flash_nuke.uf2 link
https://raw.githubusercontent.com/OpenStickCommunity/GP2040-CE/main/docs/downloads/flash_nuke.uf2
- Update create an issue link …
> Shortcuts and formatting updates for docs.

- configs/BentoBox/BoardConfig.h
- configs/DURAL/BoardConfig.h
- configs/FightboardV3/BoardConfig.h
- configs/FightboardV3Mirrored/BoardConfig.h
- configs/FlatboxRev4/BoardConfig.h
- configs/FlatboxRev5/BoardConfig.h
- configs/MavercadeKeebfighter/BoardConfig.h
- configs/Pico/BoardConfig.h
- configs/PicoAnn/BoardConfig.h
- configs/PicoFightingBoard/BoardConfig.h
- configs/SparkFunProMicro/BoardConfig.h
- configs/WaveshareZero/BoardConfig.h
- headers/storagemanager.h
- src/addons/extra_button.cpp
This does away with magic numbers for Dpad related defines in BoardConfig.h.
This also fixes a bug that would have occurred with Right Dpad button.
The defines are located in GamepadState.h and are:
GAMEPAD_MASK_DU
GAMEPAD_MASK_DD
GAMEPAD_MASK_DL
GAMEPAD_MASK_DR
> Switch extra button Dpad mask to defines instead of magic numbers

- headers/addons/bootsel_button.h
- headers/addons/dualdirectional.h
- headers/addons/extra_button.h
- headers/gamepad/GamepadEnums.h
- headers/gamepad/GamepadState.h
- src/addons/bootsel_button.cpp
- src/addons/dualdirectional.cpp
- src/addons/extra_button.cpp
- src/addons/i2cdisplay.cpp
Along with the FIP SOCD mode, this PR fixes SOCD for addons like Extra button and BOOTSEL button addons.
Besides that, the SOCD behaviour for Dual Direction addon might need reviewing/testing.
Closes: https://github.com/OpenStickCommunity/GP2040-CE/issues/168
> Implement SOCD mode First Input Priority

- configs/Pico/BoardConfig.h
- src/gamepad.cpp
This adds a method to define default parameters for Input and D-Pad mode in `BoardConfig.h`, which is optional.
Please accept if we want to support this.
> Add a way to get defaults for input and D-Pad mode

- .gitignore
- CMakeLists.txt
It would be nice to run certain commands before or after the build. This PR adds a reference to an optional file which only gets called in a non-CI environment.
Please review if this addition is OK. Thanks!
> Add reference to an optional custom CMake script

- headers/gamepad/GamepadEnums.h
- src/gamepad.cpp
With the addition of the First Input Priority SOCD type, the hotkeys configuration list also needs to be updated. This PR addresses that.
Please review and merge, thank you!
> Add SOCD First Input Priority to hotkeys list

- src/gamepad.cpp
This fixes an issue that unnecessarily cleans F1 and F2 button masks even when a valid hotkey combo isn't pressed.
Apologies for the problem.
Please check and merge, thank you!
> Fix unwanted cleaning of F1 and F2 button masks

- src/configs/webconfig.cpp
This solves some addons settings data from being truncated as the payload size for it has gotten significantly larger due to recent development.
This has also been reported here: https://github.com/OpenStickCommunity/GP2040-CE/issues/196
Besides this, better and future-proof solution to this would be to only send what has been changed instead of every field.
> Fix addon web data truncation via payload limit

- headers/gamepad/GamepadDescriptors.h
Quick fix for gamepad descriptors
> Fix for gamepad descriptors in PS4.

- src/configs/webconfig.cpp
For any change, big or small, the addons config page sends all of the data to the board, which is inefficient and also caused a recent bug. This PR aims to send only what's updated and the firmware also accounts for fields which have been omitted.
Web-config repo has also been updated for this (https://github.com/OpenStickCommunity/WebConfigurator/pull/55).
> Send only changed values in Addons page to the board

- headers/addons/dualdirectional.h
- headers/gamepad.h
- headers/gamepad/GamepadEnums.h
- headers/gamepad/GamepadState.h
- src/addons/dualdirectional.cpp
- src/addons/i2cdisplay.cpp
- src/gamepad.cpp
This PR was created after I attempted to manually fix a mess GitHub's rebase feature caused. Please check carefully whether the contents actually make sense; it's possible something went missing (in particular, [this commit](https://github.com/henrebotha/GP2040-CE-1/commit/dcd2b6c3b9e6d89fad2f8d4503baaa153be0fdcc) and [this commit](https://github.com/henrebotha/GP2040-CE-1/commit/04d0f04e3d906fc78dfee07aabfa85b57126cc69) existed on the original branch that @deeebug made their PR against).
Fixes https://github.com/OpenStickCommunity/GP2040-CE/issues/156.
> Add option to bypass SOCD cleaning for supported input modes

- src/addons/i2cdisplay.cpp
Changed it to SOCD-X to match our other modes and make it not look like a giant blank spot.
> Quick change for no SOCD mode

- src/addons/dualdirectional.cpp
This fixes/implements Combination Mode "None" behavior for the Dual Directional Input add-on. It allows for an essentially distinct set of directional inputs that acts independently (mostly) from the "normal" set of directional inputs. For example, if the normal D-Pad Mode is set to Left Stick, and Dual D-Pad Mode is set to D-Pad, you can register them as two separate axes/hats simultaneously. The DDI inputs are SOCD cleaned as per the board's setting, again independently from the normal input's readings.
To avoid one set of inputs masking the other, when normal and dual D-Pad are set to the *same* mode, as in both are for example in D-Pad mode, they are bitwise ORed together and SOCD cleaned in tandem. Without the bitwise OR, the DDI D-Pad would overwrite whatever was registered on the …
> Fix implementation of Dual Directional Input, Combination Mode None

- CMakeLists.txt
- headers/configmanager.h
- headers/configs/base64.h
- headers/storagemanager.h
- headers/themes.h
- lib/AnimationStation/src/Effects/StaticTheme.cpp
- lib/AnimationStation/src/Effects/StaticTheme.hpp
- src/configmanager.cpp
- src/configs/webconfig.cpp
- src/storagemanager.cpp
I have optimized the stack usage of a lot of functions, as we were having issues with stack overflows recently.
These are the functions I have optimized:
| Function | Stack usage before | Stack usage after |
|---|--:|--:|
|`fp_open_custom()` | 528 | 48 |
|`setCustomTheme()` | 1680 | 424 |
|`getCustomTheme()` | 1696 | 376 |
|`setDisplayOptions()` | 1288 | 272 |
|`getDisplayOptions()` | 1272 | 128 |
|`setLedOptions()` | 1856 | 248 |
|`getLedOptions()` | 1048 | 80 |
|`setAddonOptions()` | 1600 | 240 |
|`getAddonOptions()` | 1104 | 176 |
|`getGamepadOptions()` | 704 | 208 |
|`setGamepadOptions()` | 760 | 128 |
|`setSplashImage()` | 1184 | 168 |
|`setPS4Options()` | 896 | 128 |
|`setPinMappings()` | 616 | 328 |
|`addStaticThemes()` | 864 | 384 |
| `Storage::setDefaultSplashImage()` | 1032 | 16 …
> Stack optimizations

- docs/index.html
Release notes from the Github releases API were causing the notes sections to be displayed in sidebar, which may be unwanted and are causing layout inconsistencies.
In the following image, the sub-sections are not part of the `Installation` page.
> Escape release notes headers from showing up

- headers/addons/wiiext.h
The Wii extension addon inadvertently enables the addon and maps pins by default, causing validation issues in the web config and confusion for the user. This PR disables the extension by default and unsets the default pin mappings.
> Disable Wii extension addon by default

- src/addons/dualdirectional.cpp
Just a tiny code cleanup/improvement to my previous PR to account for the no SOCD mode change that also went in.
> use getSOCDMode in DDI None to benefit from 28d47d9f

- lib/WiiExtension/WiiExtension.cpp
- lib/WiiExtension/WiiExtension.h
- src/addons/wiiext.cpp
Added improved Wii extension detection.
Added GHWT touch fret support.
Added initial Wii extension hot plugging support.
Fixed issue with detecting GHWT guitars.
Fixed issue with guitar analog values.
Mapped taiko controller left drumpad strikes to D-Pad Left instead of Right
> Bug fixes and tweaks for Wii extension support

- headers/addons/pleds.h
- src/addons/neopicoleds.cpp
- src/addons/playerleds.cpp
Missed this update when implementing the PLED configuration. Firmware was always using the PLED_TYPE instead of the configured option.
> Fix PLED_TYPE overriding LEDOptions.pledType

- src/configs/webconfig.cpp
`setPS4Options()` did not save anything previously. This PR fixes this problem.
> Fixed PS4Options saving

- src/configs/webconfig.cpp
As discussed on Discord this PR temporarily disables the `/api/getConfig` endpoint
> Disabled /api/getConfig

- lib/nanopb/generator/nanopb_generator.py
- lib/nanopb/generator/proto/nanopb.proto
- lib/nanopb/pb.h
- proto/config.proto
- src/config_utils.cpp
- src/configs/webconfig.cpp
I extended NanoPb to allow Protobuf fields to be flagged with `(nanopb).disallow_export`. Fields with this flag will now be excluded when converting the config to JSON.
I have also reenabled the `/api/getConfig` endpoint.
> Exclude fields from JSON config export

- headers/gamepad.h
- src/gamepad.cpp
working on 4-way joystick mode toggling in another branch, it was random whether or not I "landed" on set or unset. I identified this as the hotkey code not properly tracking lastAction.
before this change, while a hotkey was held, the action would be applied every time hotkey() was called, e.g. every millisecond, because lastAction was always NONE. this was only checked on the Y-axis toggle, but is now checked on all hotkey actions, as it also allows us from calling save() unnecessarily.
following this change I no longer experience the ambiguity on where I "land" for hotkeys that toggle a setting
> only trigger a hotkey action once per press

- src/gamepad.cpp
this allows the rest of the gamepad code --- hotkeys, BOOTSEL boot hotkey --- to always treat S1 as S1 and A2 as A2, rather than having to also encapsulate the switch check in order to have consistent behavior. the switch is only for PS4 mode anyway, so we can just stuff it in there.
fixes #329
> move PS4 TP/Share switch check to getPS4Report

- headers/helper.h
- headers/themes.h
- lib/AnimationStation/src/Animation.hpp
- lib/AnimationStation/src/Pixel.hpp
- lib/FlashPROM/src/FlashPROM.h
- src/addons/neopicoleds.cpp
- src/configs/webconfig.cpp
This PR reduces the memory usage (in webconfig mode) from 138 kb to 109 kb.
I achieved these improvement with the following changes:
*   Use `inline const` or `constexp` instead of `static const` in headers. The latter creates a new instance of the constant for each translation unit that includes the header, whereas the former creates a single instance for all translation units.
*   Converted global variables to local variables when possible
*   Converted constants with allocating types (i.e. `std::vector`, `std::string`) to non-allocating types (i.e. `C arrays`, `C strings`). The latter can be used directly from flash, whereas the former need to be copied to an allocated memory block first.
> Reduce memory usage

- src/configs/webconfig.cpp
Previously `/api/setConfig` would not initialize the config before parsing the JSON. This could lead to Protobuf encoding errors or random data being written. With this PR the config is initialized to default values.
> /api/setConfig initializes config with defaults before saving

- .github/workflows/cmake.yml
- configs/AlpacaOwO/BoardConfig.h
- configs/AlpacaOwO/CMakeLists.txt
- configs/AlpacaOwO/README.md
(This was moved from FeralAI/GP2040#71, rebased to the current config format.)
Project: https://github.com/Project-Alpaca/Alpaca-OwO
This is a board with SPI/I2C/basic UART pins routed out in a non-obstructing way to maximize the I/O flexibility, while still maintaining the standard PS360/Brook Fighting Board pinout and form factor.
This follows the pinout of v1.11 hardware. However the pinout should be considered stable and will likely not change on a subsequent revision in the future.
> Add board config for Alpaca-OwO

- headers/gamepad/GamepadState.h
- proto/config.proto
- proto/enums.proto
- src/addons/dualdirectional.cpp
- src/config_utils.cpp
- src/configs/webconfig.cpp
- src/gamepad.cpp
- www/server/app.js
- www/src/Pages/AddonsConfigPage.jsx
- www/src/Pages/SettingsPage.jsx
This masks off the oldest cardinal direction of a diagonal, allowing for fast switching to new cardinal directions on a lever, meant for arcade games which don't benefit from diagonals and would likely benefit from unambiguous, immediate direction change.
> Setting to treat the dpad as a 4-way joystick

- lib/TinyUSB_Gamepad/src/tusb_driver.cpp
Sorry about the error. This test code crept in somehow.
All other HID devices, tested and working.
> Fix incorrect HID report ID

- src/gamepad.cpp
the top-level check was actually somewhat redundant now that I fixed lastAction, since the toggles checked it anyway, but we can still use a similar approach to not save unless we need to.
but now, we also don't interfere with e.g. HOTKEY_HOME_BUTTON, which *should* always take effect as long as the hotkey is pressed, even if we've done it in past cycles --- but it shouldn't save, so don't request it.
fixes #360
> BUGFIX: don't check lastAction for non-toggle, non-save hotkey actions

- src/configs/webconfig.cpp
This PR fixes the compile error discovered by @chiyu521. This only happens with some versions of GCC, I am not sure which ones. However, the fix should work with all reasonably recent versions of GCC.
> Fix compile error with some GCC versions

- headers/configs/base64.h
I don't know why this wasn't complaining before, probably some nest of includes that is resolving differently now? ┐(ツ)┌
without this:
```
[ 89%] Building C object CMakeFiles/GP2040-CE.dir/home/bss/proj/pico/pico-sdk/src/rp2_common/pico_unique_id/unique_id.c.obj                                                                                                                                                    
In file included from /home/bss/proj/GP2040-CE/src/configs/webconfig.cpp:2:                                                                                                                                                                                                    
/home/bss/proj/GP2040-CE/headers/configs/base64.h: In static member function ‘static bool Base64::Decode(const …
```
> include <cstdint> to get uint32_t

- headers/addons/ps4mode.h
- src/addons/ps4mode.cpp
- src/configs/webconfig.cpp
- www/src/Pages/AddonsConfigPage.jsx
This is a smaller scale refactor than #374.
Notable changes:
- Frontend now uses Promise.all to load all required files.
- RSA key loading from config and identity exporting after signing are now done in mbedTLS API.
- Cut down redundant RSA factors in config storage. Now it only saves N, E, P and Q to the config and calculates the rest of the factors during setup(). This should save around 900 bytes of config storage.
> Refactor PS4 auth

- www/src/Pages/AddonsConfigPage.jsx
The isNil was incorrectly imported, uploading **might** have given false positives or not worked at all prior to this change.
This also reduces the size of the bundle by about 80kb.
> Correctly import isNil

- src/gamepad.cpp
The capture button hotkey now presses S1 (unless we're in PS4 mode and the toggle is on, in which case it presses A2).
Note that this hotkey does something even on the input modes that don't actually have a capture functionality, for clarity's sake.
> fix HOTKEY_CAPTURE_BUTTON

- src/config_legacy.cpp
PR #321 changed one of the `struct`s in `config_legacy.cpp`. We can never do that, our pre-Protobuf migration process relies on these `struct`s not changing.
I have undone the changes and added a comment at the top of the file to prevent such errors in the future.
This PR **must** be merged before the next release. Otherwise, users may experience failed configuration migrations.
> Removed harmful changes to config_legacy.cpp

- headers/build_info.h
- src/gp2040.cpp
Note this can only document the defaults, since it's baked into the firmware binary and not dynamically generated at runtime. Demo:
```
bss@garnet ~/proj/GP2040-CE % picotool info -a
Program Information
name:          GP2040-CE
version:       0.7.2
features:      double reset -> BOOTSEL
binary start:  0x10000000
binary end:    0x100b4e90
Fixed Pin Information
5:   L2
6:   R2
7:   B2
8:   B1
9:   L1
10:  R1
11:  B4
12:  B3
13:  S2
14:  A1
15:  S1
16:  Left
17:  Right
18:  Down
19:  Up
20:  A2
21:  L3
22:  R3
Build Information
sdk version:       1.5.0
pico_board:        pico
boot2_name:        boot2_w25q080
build date:        Jul 13 2023
build attributes:  Release
Device Information
flash size:   16384K
ROM version:  3
```
I want to do more of this kind of thing, but for now this is a tiny …
> Document default pin mappings in the built binary

- src/configs/webconfig.cpp
Removing used pins in webconfig.cpp as it breaks our add-on pin logic. This will need to be reworked
> Removing used pins logic in analog pins

- headers/gp2040.h
- src/gp2040.cpp
Simple enough. I wrote this because I usually want to bounce between gamepad and boot USB mode, and less so webconfig mode. I put it on S1 + B3 + B4 to match the behavior of the webconfig reboot.
Aside from adding the mask check, most of this is just renaming the struct to reflect that it has two hotkeys in it now.
This is ready to go, AFAIK, but I'm marking it as a draft because I don't think there's any reason to rush it for 0.7.3.
> add a BOOTSEL reboot hotkey to the "secret" hotkeys

- configs/Pico/BoardConfig.h
- headers/addons/keyboard_host.h
- proto/config.proto
- src/addons/keyboard_host.cpp
- src/config_utils.cpp
- src/configs/webconfig.cpp
- src/gp2040.cpp
- www/server/app.js
- www/src/Locales/en/AddonsConfig.jsx
- www/src/Pages/AddonsConfigPage.jsx
This is meant to fix #389.
Thanks to @InfraredAces for figuring out this issue and for the amazing hardware built to test this!
I do not own proper hardware to test this one in a good way, so assistance is appreciated.
The newly added pin setting is optional and for those who know what they're doing.
Edit: The addon has been enabled for testing purpose. It can be disabled if there are difficulties in making the merge.
Please check and merge, thanks!
> Add 5V Power Pin option in Keyboard Host addon

- headers/gamepad.h
- headers/storagemanager.h
- proto/config.proto
- proto/enums.proto
- src/config_utils.cpp
- src/configs/webconfig.cpp
- src/gamepad.cpp
- src/storagemanager.cpp
- www/server/app.js
- www/src/App.jsx
- www/src/Components/Navigation.jsx
- www/src/Locales/en/Index.jsx
- www/src/Locales/en/Navigation.jsx
- www/src/Locales/en/ProfileSettings.jsx
- www/src/Locales/en/SettingsPage.jsx
- www/src/Pages/ProfileSettings.jsx
- www/src/Pages/SettingsPage.jsx
- www/src/Services/WebApi.js
Working:
* config section defines up to three three alternative action button slots
* hotkey actions to switch to them
* the actual application of profiles (2-4 overlay the total core mappings in the base settings, which is profile 1)
* config option to store selected profile
* exposing the alt mappings in the API
* web configurator profile setting page w/i18n
* actual board saves and intended behavior confirmed and checked with binary-tools
* above for directionals
> Ability to switch between action/direction button profiles

- src/storagemanager.cpp
I apparently accidentally refactored this away, so adding it back
> Set the profile number in the config after switching

- src/addons/keyboard_host.cpp
- src/gp2040.cpp
- src/gp2040aux.cpp
- src/usbhostmanager.cpp
This fixes our USB host manager start sync, and we can now run PIO state machines on both the PIO PICO USB configuration and the NeoPico PIO code samples.
The reason Core1 worked before is we had to init NeoPico BEFORE we did PIO USB.
> Fixing PIO state machines 

- proto/enums.proto
- src/addons/board_led.cpp
- www/src/Pages/AddonsConfigPage.jsx
Added PS4/PS5 authentication to board-led add-on. The light turns on after authentication occurs.
> Add PS4/PS5 authentication to board-led add-on

- src/configs/webconfig.cpp
- www/server/app.js
- www/src/Components/CaptureButton.jsx
- www/src/Components/Section.scss
- www/src/Locales/en/CaptureButton.jsx
- www/src/Locales/en/Index.jsx
- www/src/Locales/en/PinMapping.jsx
- www/src/Pages/PinMapping.jsx
- www/src/Services/WebApi.js
This PR adds a new functionality to the Pin Mapping configuration screen. It allows the user to press buttons on their controller to assign pins. It can be done for each button individually or all buttons one-by-one.
Currently, as per the implementation, it initializes all valid pins. Within a window of 5 seconds, if the user does nothing, it returns empty. Before anything is returned, all unused pins are also uninitialized.
> Add feature to capture button held pins from board

- lib/AnimationStation/src/Animation.hpp
- lib/AnimationStation/src/AnimationStation.cpp
- lib/AnimationStation/src/Effects/Chase.cpp
- lib/AnimationStation/src/Effects/Rainbow.cpp
- src/addons/neopicoleds.cpp
Fix for https://github.com/OpenStickCommunity/GP2040-CE/issues/431, animation state breaks for cycling animations when they are made too fast. 
Also includes a fix to a potential memory corruption via Animation pointers in the AnimationStation.
Another small change to the RBG struct constructors to make them Trivial classes.
Please note, as my hitbox has not yet arrived I am unable to test these changes past simply ensuring they compile.
> Small fixes to LED Animation system

- src/gp2040.cpp
This is a simple fix that allows input addons to use the hotkeys feature.
This was tested on the Keyboard Host addon and is to be noted that the boot selection (selection of controller types/web-config) didn't work due to the delay in USB initialization which might not be present in other addons.
Please test and merge, thanks!
> Fix hotkeys with input addons

- src/config_utils.cpp
This PR fixes a problem with `setHasFlags()` discovered by @deeebug. Previously, the function did not correctly handle Protobuf repeated fields containing sub-messages. With this fix, the workaround of manually setting `has_XXX` flags is no longer necessary.
> setHasFlags() correctly handles PB repeated fields

- headers/addons/reverse.h
- src/addons/reverse.cpp
Fix for [#498](https://github.com/OpenStickCommunity/GP2040-CE/issues/498)
Reverse Inputs addon would break all dpad inputs if they were assigned to high pins ( pin 8, mask >= 256 ).
This was due to truncation of the mask in the ReverseInput::input parameters.
Recreated and fixed with standard pico:
Reverse pin 22
DPad pins: 6 7 8 9
This caused 8 and 9 to not function before the fix.
> Truncated mask broke high pin dpad inputs

- docs/app.js
https://gp2040-ce.info//#/download?RP2040AdvancedBreakoutBoard
Not the cleanest solution as the user will end up on the download page before the uf2 gets download, might be good enough for now.
The board name in the search param is case insensitive
> Added a redirect to uf2 based on url

- src/addons/tilt.cpp
- Modified the code to allow Tilt1 and Tilt2 to function even if they are not mapped to any pins.
- This change makes the Tilt1 and Tilt2 features more flexible and allows users who do not require PinMapping to still benefit from these functionalities.
- Tests have been carried out to ensure that the features work as expected both when pins are mapped and when they are not.
Please review and let me know if any changes are required.
> Feature: Allow Tilt1 and Tilt2 to Operate Without PinMapping

- README.md
- docs/usage.md
- docs/web-configurator-add-ons.md
I wanted to make some changes to the docs to help with discoverability of some features, most notably for add-ons. I'm not an expert on markdown, so the links for now are URL links instead of links between markdown pages. 
Summary of changes:
`README.md`: added a link to the github page (as far as I know, this is the page that generates https://gp2040-ce.info/, and there was no link back to the github repo) and a direct link to Turbo functionality under the features list. In future this could be expanded to direct link all the features to their documentation, but I'm leaving it for now so that this PR can be incremental
`docs/usage.md`: I pulled the paragraph from InfraredAces on discord from our discussion to replace the "unfinished docs" section on turbo and analog stick emulation, but …
> Update docs with minor improvements for add-on discoverability

- headers/gamepad.h
- headers/gp2040.h
- headers/gp2040aux.h
- lib/TinyUSB_Gamepad/src/tusb_driver.cpp
- lib/TinyUSB_Gamepad/src/usb_driver.h
- src/gp2040.cpp
- src/gp2040aux.cpp
Need to do more testing on this, but this matches what @mthiesen originally thought about removing sleeps. I think the missing piece was not clearing feature data and requesting a "get report" if the endpoints are busy.
I need to test this more, so this is a draft copy
> Full sleep removal from core0 and core1 loops

- docs/app.js
- docs/package.json
- Links don't need target="_blank" (reported by @jfedor2 in discord)
- Fix links for closed source devices(https://github.com/OpenStickCommunity/GP2040-CE/issues/492)
- Now opens a browser when starting the docs locally.
- Download links now works in local mode
> Fixing links in docs

- docs/app.js
- docs/index.html
- docs/site.css
**Could not find a way to search for dynamically generated content in "Downloads"**
Before merging it might be worth considering if this caveat is a deal-breaker.
> Adds search functionality to https://gp2040-ce.info/

- headers/addons/i2cdisplay.h
- headers/addons/neopicoleds.h
- headers/addons/pleds.h
- lib/TinyUSB_Gamepad/src/tusb_driver.cpp
- lib/TinyUSB_Gamepad/src/usb_driver.h
- proto/config.proto
- src/addons/i2cdisplay.cpp
- src/addons/neopicoleds.cpp
- src/addons/playerleds.cpp
- src/config_utils.cpp
- src/configs/webconfig.cpp
- www/server/app.js
- www/src/Locales/en/DisplayConfig.jsx
- www/src/Locales/en/LedConfig.jsx
- www/src/Pages/DisplayConfig.jsx
- www/src/Pages/LEDConfigPage.jsx
This adds an option to have the RGB LEDs, Player LEDs and the OLED Display turned off when the host (PC, console, etc.) goes to sleep.
This hasn't been tested on a console, but should function as per the USB protocol.
> Add option to turn off RGB & OLED on host suspend

- www/src/Addons/Ps4.tsx
I wasn't able to get the PS4 Mode addon to work, it just showed the following error at me after clicking Verify and Save:  'ERROR: Could not verify required files: ${e}'
Turns out that was a string literal instead of a template. Replacing the ' with ` in Ps4.tsx made it a template and enabled printing the actual error.
The actual error was that WebAPI wasn't found. I added the missing import and it started working.
> Fix error display string template in Ps4.tsx. Add missing Web API import.

- docs/installation.md
- docs/introduction.md
- docs/site.css
- docs/templates.md
- docs/web-configurator.md
* Add `md` tag to code blocks containing markdown
* Remove unnecessary whitespace
* Fix a typo in a list
* Convert "Linux Setup" to an h2, as there should only be one h1
> Minor documentation cleanup

- src/addons/dualdirectional.cpp
- src/gamepad.cpp
This addresses Example 1 of #532 without any immediately obvious detriment to the 4-way/SOCD interaction, other than it has an order of operations problem (L > D > R = nothing, but R > D > L = L).
However, #533 fixes that issue by implementing filtering better, and it fixes Example 2 of #532.
@TheTrainGoes is going to do more testing, but in my testing, these two PRs together fix #532.
> run 4-way filtering before SOCD cleaning

- src/gamepad.cpp
There's been observable drops in inputs when report counter is missing in the PS4 reporting structure.
Playing "Ultimate Chicken Horse" on PS5, it is observed that rapid inputs will eventually cause the gamepad to lock when report counter is missing.
Still confirming adding report counter back in fixes the issue, but it appears it is important somewhere in the gamepad stack on the PS4/PS5.
> Moving report counter back into PS4 with proper 6-bit roll-over

- www/src/Data/Buttons.js
- www/src/Pages/LEDConfigPage.jsx
- www/src/Pages/PinMapping.jsx
- www/src/Pages/SettingsPage.jsx
while setup fn hotkeys on page Settings  ,  i found it hard to setup hotkeys,  cause not familiar with gp2040 button label names
here minor changes in  jsx to  show button label   by   current  button label type ( ps4 , gp2040,  etc..)type
before
after 
change 1:  setting page,  hotkeys  show  buttons  by  current button label type
change 2:  configuration>>pin mapping page,  show function pin input   in pin page , for button label type is ps4
> web settings  : show button label according to current button  lable type

- docs/usage.md
Currently both Xinput and DirectInput/PS3 Modes are labeled in usage.md as being invoked by B2. This is to change the DirectInput/PS3 button to be B3.
> Change target button for DirectInput/PS3 Mode in documentation

- headers/addons/wiiext.h
- src/addons/keyboard_host.cpp
- src/addons/wiiext.cpp
- src/gamepad.cpp
- www/src/Addons/Wii.tsx
Allow digital input state and analog value state to co-exist for triggers when Gamepad.hasAnalogTriggers is true.
Added analog trigger check for keyboard host to avoid potential issues.
> Update analog trigger mode to include digital state

- configs/Pico/BoardConfig.h
- src/config_utils.cpp
This adds a missing initialization entry for enabling the On-Board LED addon via the `BoardConfig.h`.
> Fix default On-Board LED enable issue

- configs/Pico/BoardConfig.h
- docs/add-ons/tilt-input.md
- headers/addons/tilt.h
- src/addons/tilt.cpp
- www/src/Addons/Tilt.tsx
Reworked @InfraredAces #577 to include the recent Analog middle value changes from #582.  Also refactors the state checking when pressing the modifiers to remove redundant logic.
> Tilt state refactor and analog mid adjustments

- src/addons/i2cdisplay.cpp
The update changes the default display layout so that the word 'SOCD' remains while also allowing for the macro M and clear identifiers for DPad / Left Stick / Right Stick
> Update to the default config layout

- configs/Pico/BoardConfig.h
- configs/PicoW/BoardConfig.h
- proto/config.proto
- src/config_utils.cpp
- src/configs/webconfig.cpp
This addresses the following identified issues:
* gpioMappings losing mappings on GPIO 0 and 1 due to erroneous detection of enabled addons
* being unable to un-ASSIGNED_TO_ADDON the PLED pins when setting them to -1 in webconfig
* (re)initializing the deprecated buttonMappings for no reason
It does not address:
* the fact PLEDs are migrated as ASSIGNED_TO_ADDON when not in use because some BoardConfig.h files nevertheless enabled them
* the large growth of fsdata.c
> Fixes to gpioMappings migration and webconfig

- .github/workflows/deploy.yml
- site/docs/development/firmware-development.mdx
- site/docs/downloads/download-page.mdx
- site/docs/hotkeys.mdx
- site/docs/rgb-leds.mdx
- site/docs/usage.mdx
- site/docs/web-configurator/web-configurator.mdx
This PR changes the documentation deployment process from committing to the `gh-pages` branch and then running the `pages build and deployment` action to running a single action, `Deploy to GitHub Pages`, on push to main. It also removes the need to have a personal access token and additional commit from the PAT holder.
Additional minor documentation updates were included in this PR.
- Change the `Build and deployment` source from `Deploy from a branch` to `GitHub Actions`.
Once these changes are made, the original PAT can be removed from the repo secrets and the `gh-pages` branch deleted.
> Documentation - Update workflow to use Github Action to deploy

- src/configs/webconfig.cpp
This resolves a webconfig crash where setting an addon pin from -1 to -1 would crash the board until it was powercycled.
> docToPin: only unset the old pin to NONE if it's a valid pin

- site/docs/hotkeys.mdx
The home button and SOCD hotkeys did not have their default bindings. They have been added for consistency.
> Added default hotkeys to descriptions

- headers/storagemanager.h
- proto/config.proto
- src/config_utils.cpp
- src/configs/webconfig.cpp
- src/storagemanager.cpp
! ! ! WARNING ! ! !
Current users of `main` will find their config is wiped by this change. You will have to go into webconfig and redo your config. 0.7.5 users should be unaffected.
My Python-brain wrote `GpioMappings` in a descriptive way that's great for dynamic languages, but it turned out that in our code, I had to quickly treat the dict-like message in protobuf as an array in C, to make it easy to work with. This was fine, but a bit funky, and kept the protobuf descriptive. However, this array pattern would have to have been duplicated for profiles-as-GpioMappings, which would have meant more funky code and more stuff residing in memory for no good reason. This has the mappings as an array in the protobuf, which is slightly less obvious when reading a protobuf config, but this may …
> convert GpioMappings to an array in protobuf

- headers/gamepad.h
- headers/gp2040.h
- headers/storagemanager.h
- src/gamepad.cpp
- src/gp2040.cpp
- src/storagemanager.cpp
GPIO fiddling was in the Gamepad object, which was fine, but it's going to make more sense in the future for the GP2040 object to manage it, since it has references to addons which will be affected by profile changes, pending another refactor.
this has us essentially initialize/deinitialize "normal" GPIO pins in the higher object and then gamepad and addons just need to worry about button masks or whatever, regardless of the pin initialization itself
> refactor profile switching to be managed by the GP2040 object

- configs/Haute42/BoardConfig.h
Changes the board label to `Haute 42` from `Pico`
> Update to Haute42 config

- headers/gamepad/descriptors/PS4Descriptors.h
- src/gamepad.cpp
PS4/PS5 have an axis-timing counter that is 16-bit. We just ignored it but its good to have!
> Added axis-timing counter (increment 1 every input) to PS4 descriptor

- headers/gamepad/GamepadConfig.h
- proto/config.proto
- src/config_utils.cpp
- src/configs/webconfig.cpp
- src/gamepad.cpp
- www/server/app.js
- www/src/Locales/en/SettingsPage.jsx
- www/src/Pages/SettingsPage.jsx
PS4 reporting is a hot topic.
This adds a switch to our web config so you can turn on a hack that disables report counters in the PS4/PS5 reports. This brings PS4/PS5 latency down to around 0.8ms, but could have potential instability in certain games.
> Added PS4 report speed hack to web config

- CMakeLists.txt
This should fix an issue Hylian on the discord ran in to with running the build outside of the repo root, and while I was in there, I noticed that I didn't add `--dirty` which is helpful for tracking when you have builds with uncommit changes.
> flag dirty git versions, and set git describe's cwd

- site/docs/usage.mdx
- site/docs/web-configurator/web-configurator.mdx
Made changes to documentation describing the hotkey combinations to access webconfig and bootsel while the controller is plugged in.
> Added information about hotkey access to webconfig and bootsel while controller is plugged in

- headers/gamepad.h
- lib/TinyUSB_Gamepad/src/tusb_driver.cpp
- src/gamepad.cpp
In order to increment sequence on key press in Xbox One, we have to keep track of last report sent.
This is slightly tricky because report generation does not guarantee a report is sent.
- So, if our last report sent input != current report sent, set sequence for this report to +1 but don't increment.
- ON SUCCESS, increment report by 1 and update our last sent report.
> v0.7.6-RC2 FIX: Xbox One input-fix

- src/configs/webconfig.cpp
`docToPin` and our USB D+/D- handling code only managed the core profile configuration, but it also needs to set the fields in profiles.
fixes #667
> v0.7.6-RC3 Fix: manage ASSIGNED_TO_ADDON profile pins as well as core pins

- headers/gamepad.h
- src/addons/i2cdisplay.cpp
- src/addons/turbo.cpp
This PR adds smaller rings to buttons on the OLED when turbo is active.
Currently this has only been done for the following layouts:
- SticklessB
- Vewlix8
- Noir8
> Add turbo rings to display for some layouts

- headers/addons/dualdirectional.h
- src/addons/dualdirectional.cpp
This fixes the misbehavior described in #559 item 3, where 4-way didn't work properly if it was enabled for both the core gamepad and DDI at the same time. @sirrow is the author, I have just pulled, reviewed, and tested it.
Fixes #559.
> Fix 4-way mode when enabled for both core gamepad and DDI

- proto/config.proto
- src/addons/neopicoleds.cpp
- src/config_utils.cpp
- src/configs/webconfig.cpp
- www/server/app.js
- www/src/Pages/LEDConfigPage.jsx
- www/src/Services/WebApi.js
I missed/lost track of the fact that pledPin1-4 are only true GPIOs in PWM mode, and RGB mode uses the same fields as generic indexes instead. this is of course a wreck for tracking in GpioMappings, so I added new pledIndex1-4 fields for use in RGB mode, letting pledPin1-4 be truly just for GPIO pin assignments in PWM mode (or set to -1 otherwise).
furthering the confusion, the web UI *already* referred to pledIndex1-4, just it copied the value of those states back and forth to/from pledPin1-4, so now that the API has those fields as real fields, I just had to remove the copying.
I don't have PLEDs so all I was able to test is that protobuf does what it should now, and only when PWM pins are set do they get reserved in GpioMappings. tested on a nuked board, with webconfig allowing for …
> v0.7.6 FIX: deduplicate the PLED PWM GPIOs vs. RGB indexes

- src/configs/webconfig.cpp
Solves the issue of not being able to navigate to /backup directly
> Add backup route to spa paths in webconfig, remove extra spaces

- www/src/Contexts/AppContext.jsx
Solves the issue of the addons page thinking all addons are enabled even when disabled.
Current we have this issue: 
The `is` check is always compared against the [checkbox/toggle](https://github.com/OpenStickCommunity/GP2040-CE/blob/aa48d716c654b55da66d0e955576d3844c832e5d/www/src/Pages/AddonsConfigPage.jsx#L204) value for the addon section, meaning it's either `1` or `0`
Yup validation for `is` does a strict equal hence not being able to do `is: true`
This change is equivalent to 
```javascript
is: (value) => value === 1
```
If we feel that is more explicit
More info: https://github.com/jquense/yup?tab=readme-ov-file#schemawhenkeys-string--string-builder-object--values-any-schema--schema-schema
> Validate addon settings when enabled

- src/config_utils.cpp
without this, protobuf will initialize the fields to 0 before the migration runs, which is a valid pin, leading to botched settings on fresh boards
> reinitialize slider and DDI legacy settings

- headers/addons/i2cdisplay.h
This PR updates i2cdisplay.h's `HAS_I2C_DISPLAY` to 0 which was current set as -1 and causing issues.
This was only discovered now that we are stripping unused instances of `HAS_I2C_DISPLAY` out of configs where not used.
> Update to i2cdisplay defined values

- src/configs/webconfig.cpp
This update fixes a bug in webconfig.cpp which did not allow you to `mirror` or `mirror + flip` a display.  This is because originally we only had two values (`none` and `flip`) and they were set in webconfig.cpp as 0-1.  That has been removed and now all four modes can be used.
> Updated webconfig.cpp to fix flipping display bug

- src/addons/keyboard_host.cpp
Fixes regression for #764 and reverses a change made in #658
> Fixed keyboard host dpad up/down directions

- src/gamepad.cpp
~~This does some trickery with the report increments to use them to force a PS4 report roughly every 7ms (there's no particular design behind this value, it's just the result after I looked at some docs)~~ This puts a forced report with new counter values on a ~~17~~ 1000 ms timer, which fixes games that expect occasional reports, meaning we may not need the PS4 Hack anymore.
Shoutout to @TheTrainGoes for doing some quick latency testing. See the last comment for updated timer-based latency results, they are better than the old methodology anyway.
The latest results are virtually no increase over the measured 0.86 ms (in the README) for PS4 Hack mode, and considerably better than the 1.72 ms measured without the hack. A game thinking the inputs are stuck will have a new report every …
> PS4 latency improvement: force occasional reports (with new counters) in PS4 mode to reduce the need for the PS4 Hack

- src/addons/jslider.cpp
I'm not going to say we *understand* why this fixes #790, but it appears to.
> use if-else block logic instead of switch in jslider debouncer

- www/src/Pages/PinMapping.tsx
https://github.com/OpenStickCommunity/GP2040-CE/assets/5345892/f3ecccaa-8b86-4d01-ab4b-ca4114ee49a8
Solves a regression bug from the pin rework, issue found by thetrain
> Make sure the action button labels update when changing mode

- lib/AnimationStation/src/Animation.cpp
- lib/AnimationStation/src/Animation.hpp
- lib/AnimationStation/src/AnimationStation.cpp
- lib/AnimationStation/src/AnimationStation.hpp
- lib/AnimationStation/src/Effects/CustomTheme.cpp
- lib/AnimationStation/src/Effects/CustomTheme.hpp
- lib/AnimationStation/src/Effects/CustomThemePressed.hpp
- proto/config.proto
- src/config_legacy.cpp
- src/config_utils.cpp
- src/configs/webconfig.cpp
- src/storagemanager.cpp
The Custom theme now supports blending the pressed color back into the regular color.  
https://discord.com/channels/1049366310389289001/1049370387563163731/1197730363015962844
Use parameter up/down (S1+S1+(R1/R2)) to increase or decrease the fade.   Defaults to 0ms blend which is the current behaviour.
> Custom theme pressed color variable fade

- headers/usbhostmanager.h
- src/system.cpp
- src/usbhostmanager.cpp
This fixes the first-boot and reboot issues we were seeing on Xbox One with the dongle plugged in. We have to tell TinyUSB Host to shut down the bus/port before we perform the soft reeboot.
Added a shutdown() feature to USB Host Manager to take care of Controller -> Web Config -> Controller bad behavior.
> Fix for Xbox One / USB Host Soft-Reboot

- src/addons/i2cdisplay.cpp
**Changes:**
Inner turbo rings/squares added to more button layouts.
1. Keyboard (MAME)
2. Keyboard8 (MAME8)
3. OpenCore0WASD
4. VLX
5. Vewlix7
6. Sega2p
7. Capcom
8. Capcom6
9. Buttons Angled (WASD)
10. Arcade
Inner squares example:
Inner circles looks the same as layouts that already had turbo rings.
**Question:**
Should I have opened an issue first stating a new addition and if I was going to work on it then make a pull request?
> Added turbo rings/squares to more layouts

- configs/Stress/BoardConfig.h
Putting this here to build it, but it should work!
> Stress - Switch incorrect pin 3 for pin 2

- headers/drivers/hid/HIDDescriptors.h
- src/drivers/hid/HIDDriver.cpp
PS3 face buttons are technically analogs like L2/R2. they were declared in the payload but never used, but apparently Marvel vs. Capcom 2 uses the analog values, so use the digital button state to populate the fake "analog" values and get the game working.
this also confirms the order of the axes declared in HIDDescriptors.h, which is nice.
this *ALSO* means MvC2 (and who knows what else) has a predefined notion of what's in the payload bytes despite the interface descriptor, so that's interesting, but whatever
I WANNA TAKE YOU FOR A RIDE
Fixes #785
> populate the PS3 analog values for buttons

- headers/drivers/neogeo/NeoGeoDescriptors.h
- src/drivers/neogeo/NeoGeoDriver.cpp
This should allow the side panel Options button and 4 extra action buttons to be included where used.
Assume the following mapping, as the remaining 4 buttons are unlabeled (using L1/L2/R1/R2 naming).
```
A C R1 L1
B D R2 L2
B3=A
B1=B
B4=C
B2=D
S1=Select
S2=Start
A1=Options
L1=L1
L2=L2
R1=R1
R2=R2
```
This should help to resolve #844 .
> Added button masks for Neo Geo ASP extended buttons

- src/addons/buzzerspeaker.cpp
Buzzer speaker had an off-by-one issue. So the last note would read from memory, and in some cases cause a "fart" noise
> Buzzer Speaker off-by-one fix

- headers/gp2040.h
- headers/peripheralmanager.h
- src/gp2040.cpp
This is the correct fix for PeripheralManager as a singleton
> Corrected fix for PeripheralManager as a singleton

- compile_proto.cmake
It looks like the cmake generation of enums and config proto could run out of order and cause a strange race condition on Github runners.
Combining these two into a single custom command fixes the ordering and no longer fails.
> Combine enums and config proto generation

- headers/drivers/ps4/PS4Driver.h
- src/drivers/ps4/PS4Driver.cpp
Instead of sending a forced report every X ms no matter what, this moves the forced report to only occur when the new report matches the last sent report for X ms, since if the user is creating lots of valuable (changing) input, we don't need to force one.
I think 250ms is fair in this new model, but we can test it later and bump it up to say 500ms if we don't like 250ms for whatever reason. 250ms seemed like a good compromise between stuck inputs and minimal effect on active gaming, but we can dial it in.
> PS4 de-hack: only force a report when the reports are otherwise idle

- configs/Pico/BoardConfig.h
Tihs PR reverts the Pico config to its original state which had  Turbo, Turbo LED, board LED and the OLED display on by default.
This was originally removed because of conflicts that could occure but we have a more robust web-config setup now.
This will address a number of issues for people that have purchased generic devices on AliExpress which were designed around the original configuration.
> Update BoardConfig.h for Pico config

- src/addons/board_led.cpp
- src/addons/keyboard_host.cpp
- src/addons/snes_input.cpp
- src/addons/tilt.cpp
- src/addons/wiiext.cpp
- src/gamepad/GamepadState.cpp
This should fix issues with state updates before the driver has been declared. We might want to revisit assigning mid to a Gamepad variable instead of pulling from the driver input, but this will fix crashing issues for now.
> New Driver System - Fix bug for Wii/Tilt/few others

- headers/addons/buzzerspeaker.h
- proto/config.proto
- src/addons/buzzerspeaker.cpp
- src/config_utils.cpp
- src/configs/webconfig.cpp
- www/server/app.js
- www/src/Addons/Buzzer.tsx
- www/src/Locales/en/AddonsConfig.jsx
Added optional enable pin to to allow toggling the sound on/off when necessary. The enable pin is pulled high on setup() if the pin is defined so it will need to be brought low to disable the speaker during runtime.
> Buzzer Speaker enable pin

- www/src/Locales/en/PinMapping.jsx
- www/src/Pages/PinMapping.tsx
- www/src/Store/useProfilesStore.ts
Still requires saving after copying, copy/design suggestions or is this ok?
> Adds button on each profile mapping to copy from base profile

- headers/addons/turbo.h
- src/addons/turbo.cpp
My previous Turbo update PR assumed the LED was active low, so the LED current would sink from +V. This caused incorrect and odd LED behavior for the more common use case of connecting LED+ to a GPIO pin.
This PR updates the default logic to use active high to drive the turbo LED, similar to #883, but also cleans up the LED state logic and allows overriding via board config using a define. This wasn't added as a togglable option via web config, but can be added if we think it's beneficial.
I also renamed the slightly ambiguous `turboButtonsPressed` variable to `turboButtonsMask`, which @SavageCore brought up when we discussed turbo behavior.
> Update turbo LED logic

- CMakeLists.txt
- headers/display/GPGFX_UI_layouts.h
- headers/display/ui/screens/ButtonLayoutScreen.h
- headers/layoutmanager.h
- src/configs/webconfig.cpp
- src/display/ui/screens/ButtonLayoutScreen.cpp
- src/layoutmanager.cpp
Fixes:
Addresses a bug with the Input History button glyph LUT that would cause the firmware to crash when run from a Debug build state.
Enhancements:
LayoutManager was created to allow sharing of built-in and custom layouts beyond the use of the OLED Display. This also includes two new API routes for the WebConfig:
* /api/getButtonLayoutDefs
* Returns the list of ButtonLayout and ButtonLayoutRight definitions and their values.
* /api/getButtonLayouts
* Returns the layouts for the current ButtonLayout and ButtonLayoutRight definitions, as well as the LED layout indexes.
This also includes enhancements to the button layouts to change from an unnamed array of parameters to named properties.  The defined button layouts will still use the previous structure for brevity, but the names exist to …
> LayoutManager & button layout enhancements/fixes

- headers/gamepad.h
- src/gamepad.cpp
Some hotkeys are just chords of a sort for normal button outputs, and should be allowed to be held. Some refactoring accidentally undid that and had all hotkeys be checked against the previously run hotkey, such that they all only ran once until the hotkey was let go. This restores the old functionality and also guards some additional hotkeys that don't need to be held and should only run once because they are toggles and/or they save to flash.
Fixes #876
> Allow some hotkeys to be held again

- src/addons/reverse.cpp
using the core gamepad pin masks meant that anything that was adding to/modifying dpad state was being overwritten because they probably fired before reverse input, and thus their change to the gamepad state was being dropped because the GPIO pins themselves were inactive, so the reverse input logic thought the outputs were inactive and assigned to the dpad e.g. 0 | 0 | 0 | 0 | 0
this fixes reverse input + DDI entirely, and also allows the proper SOCD of the dpad(s) to be inverted rather than dropped.
note that reverse input only works against the dpad, I don't know if that's intended or not, but I'm leaving it as is.
Fixes #822
> update reverse input to work on the dpad state rather than pin masks

- www/src/Pages/CustomThemePage.scss
- www/src/index.scss
This should also solve the same issue in led config page.
A quick fix for #897
https://github.com/OpenStickCommunity/GP2040-CE/assets/5345892/15742081-a597-4979-88e8-ec2f56895e2f
> Enables scroll for color picker when out of view

- src/drivers/ps4/PS4Driver.cpp
The old keepalive timer of 250ms (four forced reports when idle, per second) functioned, but was far longer than a single frame, meaning that stuck inputs could still definitely happen, just for short periods of time. This was fine when the only game we knew about was Ultimate Chicken Horse, which, while being a platformer, is not exactly the most precision-heavy game. However, we learned in beta testing 0.7.8 that the Hamster Arcade Archives also often exhibit this problem, especially games like Tetris: the Grand Master, where precision *is absolutely* important.
Turning the timer down to sub-frame (assuming 60 Hz input mechanisms) means we have a couple opportunities to force the correct input down to the PS4 within one frame, which in my testing to this point has eliminated any …
> Tweak PS4 non-hack report timer

- www/src/Components/CustomSelect.scss
Fix pin mapping page styling disabled state
> Add styling for disabled state

- www/src/Data/Buttons.js
- www/src/Pages/CustomThemePage.scss
We have not implemented being able to set color to the function button. this results in an error when pressing it.
Unsure if it was ever intended, the rendering was a biproduct of having an incorrect const.
Api does not support it either, i've removed it so the user doesn't think it's possible to change it until we are done with LED rework.
Before
After
#927
> Custom led theme

- lib/WiiExtension/extensions/GuitarExtension.cpp
- src/addons/wiiext.cpp
* Fixes issue where controller modes that support a single direction of analog movement (triggers mainly) would not function.
* Removed previous fallback calibration for guitars which was based on a broken whammy bar.
> Wii guitar range adjustments and analog trigger handling

- www/src/Components/KeyboardMapper.jsx
- www/src/Locales/en/SettingsPage.jsx
- www/src/Pages/SettingsPage.jsx
- www/src/Services/WebApi.js
This PR aims to fix fetching/validating/saving of key mappings on settings page.
One issue was that we had nested forms. therefor the key mapping form was never submitted.
As there can be only one!
As quite a bit was being changed in the file so i decided to format the file according to .editorconfig.
I kept the formatting to one [commit](https://github.com/OpenStickCommunity/GP2040-CE/commit/44ee9d3e833b045b3fa5b9132f9f53ddbbf5a0d2)
The important commits are:
https://github.com/OpenStickCommunity/GP2040-CE/commit/f4f0b883613d00ca296259c10b1e61f162c24495
https://github.com/OpenStickCommunity/GP2040-CE/commit/a327f79e9dba2440e70e605c650cfce1c406dde9
https://github.com/OpenStickCommunity/GP2040-CE/commit/7fe34263c185aeb739f82df71316c259d8b695f7
When saving input mode "keyboard" validation …
> Keyboard settings issue

- configs/FlatboxRev5RGB/BoardConfig.h
- configs/Mavercade/BoardConfig.h
- configs/OpenCore0WASD/BoardConfig.h
- configs/SGFBridget/BoardConfig.h
- configs/SGFFaust/BoardConfig.h
Updates to the board config files + small fixes.
Flatbox Rev 5 RGB - Updated to remove assigned to addon warning on for PLED chain order + removed GPIO11 which was not assigned to anything 
Mavercade - Removed EXTRA_BUTTON_MASK and replaced with new pin mapping system 
Open_Core0 WASD - Added GPIO08 to assigned to addon section for board LEDs 
SGF Bridget - Added HAS_I2C_DISPLAY 0 to address bug with board LEDs 
SGF Faust - Added HAS_I2C_DISPLAY 0 to address bug with board LEDs
> Board config updates

- headers/addons/input_macro.h
- src/addons/input_macro.cpp
- www/src/Pages/InputMacroAddonPage.tsx
The macro logic was processing macro inputs into gamepad state prior to checking if the macro needed to be reset. This resulted in repeating macros missing applying gamepad state at the end of the macro. Swapping the check for resetting the macro to before the gamepad inputs are applied and creating a `restart()` method solves this issue.
Also fixed an issue on the macro config page when adding and deleting macro actions. The deleted lines weren't being filtered out, causing no console errors but preventing any changes to the macro actions array. Fixed up the React key errors in the console for this page as well.
Addresses https://github.com/OpenStickCommunity/GP2040-CE/issues/975 & https://github.com/OpenStickCommunity/GP2040-CE/issues/976
> Macro Restart and UI Fixes

- .github/workflows/cmake.yml
- configs/ReflexCtrlGenesis6/BoardConfig.h
- configs/ReflexCtrlGenesis6/README.md
- configs/ReflexCtrlNES/BoardConfig.h
- configs/ReflexCtrlNES/README.md
- configs/ReflexCtrlSNES/BoardConfig.h
- configs/ReflexCtrlSNES/README.md
- configs/ReflexCtrlSaturn/BoardConfig.h
- configs/ReflexCtrlSaturn/README.md
- configs/ReflexCtrlVB/BoardConfig.h
- configs/ReflexCtrlVB/README.md
Drop-in USB conversions for classic controllers.
> Add Reflex CTRL Genesis-6, NES, Saturn, and Virtual Boy

- headers/addons/analog.h
- src/addons/analog.cpp
Fix bugs with two sticks only performing circularity on latter, and rapidly spinning two sticks would cause the former to jump. Rewrite to better protect against these kind of issues in the future. Other general cleanups and minor fixes.
> Analog rewrite

- www/package-lock.json
- www/package.json
- www/vite.config.ts
Formik uses lodash-es as replacement from lodash to obtain a smaller bundle size.
The web part of GP2040 uses lodash, causing both libraries to be embedded in the final bundle.
Using the alias resolve in vite built tool allows you to remove the duplication, making lodash-es as larger as necessary to cover all the functionalities that are effectively used
This removes around 9kb from the final build size
This branch
main
> build() deduplicate loadsh and lodash-es between dependencies

- headers/addons/rotaryencoder.h
- src/addons/rotaryencoder.cpp
Fixed issue where rotary encoder would occasionally max out in the opposite direction in analog joystick modes.
Fixes #998 .
> Rotary encoder joystick mode overflows incorrectly

- www/src/Services/Http.ts
- www/src/Services/WebApi.js
I noticed by chance in the [http vs axios](https://github.com/OpenStickCommunity/GP2040-CE/pull/988) PR that the signal was axios.get was merged into an header, that seems a bug to me.
Here:
https://github.com/OpenStickCommunity/GP2040-CE/pull/988/files#diff-c906511881a407b1d4a0978d708b2841f02b1a72e52c5efd1210fb16628fce6eR637
the pin mapping page is indeed pushing up this wrong header:
This is possible in the 0.78 release:
https://github.com/OpenStickCommunity/GP2040-CE/assets/1194048/0f7a7a20-b270-49f2-9757-4ce7bba27a62
But those buttons ( skip pin, cancel and the close icon ) are not functional in current master
> fix() signal from axios.get is a specific AbortSignal

- src/display/ui/screens/ButtonLayoutScreen.cpp
Input history now uses the processed gamepad for inputs to be in line with button elements
> Input history respects SOCD cleaning

- .github/workflows/cmake.yml
- configs/Blank/BoardConfig.h
- configs/Blank/CMakeLists.txt
- configs/Blank/README.md
This PR adds a totally blank configuration for people that want to build something from scratch via the web-config UI.
> Updates to add a blank configuration

- headers/addons/display.h
This will fix i2c0 enable being set to true even if i2c0 is disabled.
> Fix for i2c enabled always on

- headers/display/ui/screens/ButtonLayoutScreen.h
The icons for the home and capture buttons in the input history on Switch mode were swapped.  This RP swaps them back.
> Update to the images used for capture and home in the input history

- src/usbhostmanager.cpp
Potential fix for USB host causing reboot to lag out
> Fix for USB host causing lag on force reboot

- www/src/Pages/CustomThemePage.scss
Fixed the 16 button layout swapped the L3 and A2 positions.
> fix(layout): swap A1 and L3 buttons to correct placement issue

- src/configs/webconfig.cpp
We absolutely do not need to make the splash image memory this large.
Reduces dynamic json doc heap and allows us to take a larger post max payload
> Reduce memory allocation for getSplashImage() in web config

- www/src/Pages/PinMapping.tsx
`GPIO pin to trigger 2+ buttons` Was started before these options could be done in the pin mapping, and was missed on merge.
Now selectable again
Thanks to Hylian for finding it!
> Enables choosing turbo and macro in pin mapping

- CMakeLists.txt
- headers/addons/drv8833_rumble.h
- headers/gamepad.h
- headers/gamepad/GamepadState.h
- proto/config.proto
- src/addons/drv8833_rumble.cpp
- src/config_utils.cpp
- src/configs/webconfig.cpp
- src/drivers/xinput/XInputDriver.cpp
- src/gamepad.cpp
- src/gp2040aux.cpp
- www/server/app.js
- www/src/Addons/DRV8833.tsx
- www/src/Locales/en/AddonsConfig.jsx
- www/src/Pages/AddonsConfigPage.jsx
Adds DRV8833-based rumble functionality for XInput.
There are three main sets of changes:
1. Added a GamepadRumbleState struct, currently containing left/right motor rumble and unused stubs for left/right trigger rumble for XBone.
2. Fix some oddities with USB out endpoint writes in XInputDriver.cpp so that both LED and Rumble data is handled. Added a function in XInputDriver.cpp that checks if data in the out endpoint is rumble data and writes to GamepadRumbleState if it is.  (Sidenote: I know there's a proper GamepadAuxState WIP - I believe the writes to GamepadRumbleState can be trivially ported to GamepadAuxState when it is fully merged).
3. Added a DRV8833 Rumble Addon that reads from GamepadRumbleState and sends PWM to webconfig-defined pins that are hooked up to the DRV8833 module …
> DRV8833-Based Rumble (for XInput)

- configs/FlatboxRev5Southpaw/BoardConfig.h
This PR removes the assigned to add-on blocks in the BoardConfig.h file as they should not be there.
> Update to the FlatboxRev5Southpaw config

- CMakeLists.txt
- headers/addons/reactiveleds.h
- proto/config.proto
- proto/enums.proto
- src/addons/reactiveleds.cpp
- src/config_utils.cpp
- src/configs/webconfig.cpp
- src/gp2040aux.cpp
- www/server/app.js
- www/src/Addons/ReactiveLED.tsx
- www/src/Locales/en/Addons/ReactiveLED.jsx
- www/src/Locales/en/Index.jsx
- www/src/Pages/AddonsConfigPage.jsx
- www/src/Services/WebApi.js
This adds a basic implementation of reactive lighting using standard, non-addressable LEDs that react to ``GpioAction`` settings. Each LED has a setting for Default (not pressed) and Active (pressed) modes.
* Static On
* Static Off
* Fade In
* Fade Out
> Reactive LEDs

- src/usbdriver.cpp
Removed ``tud_hid_report`` call in ``set_report`` to prevent unexpected behavior by rebroadcasting reports. Will need to test both input modes and USB Host addons for regressions.
> Duplicate USB report sending fix

- src/usbdriver.cpp
This fixes an issue after turning on "Turn Off When Suspend" switch in RGB LED Configuration, RGB LED remains off when the usb disconnected and reconnected. so clearing the usb suspend status when the device is mounted.
> Fixed RGB LED remains off when the usb disconnected and reconnected

- headers/drivers/ps4/PS4Auth.h
- headers/drivers/ps4/PS4AuthUSBListener.h
- headers/drivers/ps4/PS4Driver.h
- headers/drivers/shared/gpauthdriver.h
- headers/drivers/xbone/XBOneAuth.h
- headers/drivers/xinput/XInputAuth.h
- src/drivers/ps4/PS4Auth.cpp
- src/drivers/ps4/PS4AuthUSBListener.cpp
- src/drivers/ps4/PS4Driver.cpp
- src/drivers/xbone/XBOneAuth.cpp
- src/drivers/xbone/XBOneAuthUSBListener.cpp
- src/drivers/xbone/XBOneDriver.cpp
- src/drivers/xinput/XInputAuthUSBListener.cpp
- src/drivers/xinput/XInputDriver.cpp
- src/main.cpp
Quick fix for getting auth back into PS5. Simple change
> Core0/Core1 Sync USB Stall fix

- src/configs/webconfig.cpp
Fixes two fatal bugs:
1. Creating a totally new profile would not have any pins on a subsequent load of the board, making using the profile lead to an inoperable controller, because the pin count wasn't retained in protobuf.
2. Creating a totally new profile would not retain the `RESERVED` or `ASSIGNED_TO_ADDON` actions, because the old code assumed other methods were populating those profiles' values, but that is not possible on a totally new profile.
> Fix initialization of new profiles' blocked pins and counts

- www/src/Locales/de-DE/SettingsPage.jsx
- www/src/Locales/en/SettingsPage.jsx
- www/src/Locales/ja-JP/SettingsPage.jsx
- www/src/Locales/pt-BR/SettingsPage.jsx
- www/src/Locales/zh-CN/SettingsPage.jsx
- www/src/Pages/SettingsPage.jsx
This fixes a bug that allows a users to select a non-existing profile, leaving the controller in a state with no pin config.
> Only allow selecting existing profiles in gamepad settings, add profile labels

- src/drivers/ps4/PS4Driver.cpp
This should address the issue where the PS features were unexpectedly enabling the lightbar on startup, as well as a number of other incorrect values in the feature report.
> PS Feature reports causing unexpected behavior on startup

- src/storagemanager.cpp
This handles both the gamepad profile number being a number that doesn't exist (even though that shouldn't be possible via webconfig), or if the profile is disabled (which could happen if the user picks profile N and then disables it afterwards). In both cases, this doesn't load the `alts` pins, so the functional pins come from profile 1.
> only load a profile if profileNum exists and is enabled

- src/gamepad.cpp
I missed the cleanup of the new LS/DP/RS mappings in gamepad.cpp. Switching a profile would leak this memory.
> Properly clean up JS mappings when switching profiles

- proto/config.proto
Just noticed that I forgot to do this in the original PR to remove the JSlider addon. It has no bearing on the running firmware and can merge whenever you want.
> flag old JSlider stuff as deprecated in protobuf

- src/drivers/ps4/PS4Driver.cpp
Fix for the PS4 touchpad 2, which caused the counter to increment when it should not have.
> PS4 touchpad boolean fix

- CMakeLists.txt
This enables generation of a `compile_commands.json` file during the build, which many IDE's and LSP servers can automatically detect and use to provide better jump-to-source, code completion, et cetera.
> Generate compile commands file used by IDE's

- www/src/App.jsx
- www/src/App.scss
- www/src/Components/Navigation.scss
- www/src/Pages/InputMacroAddonPage.tsx
- www/src/Pages/PinMapping.scss
- www/src/Pages/PinMapping.tsx
- www/src/Pages/SettingsPage.jsx
- www/src/index.scss
This is a layout suggestion to start making it more responsive.
Quite a bit of rework was need to in the macro page, hope it still makes sense.
The custom theme page overflows in smaller screens, but it still better than before.
> Add rudimentary responsive layout, rework ui in macros

- configs/MiSTercadeV2/README.md
- configs/PXPGamepad/README.md
- configs/RanaTadpole/README.md
- configs/ReflexCtrlGenesis6/README.md
- configs/ReflexCtrlNES/README.md
- configs/ReflexCtrlSNES/README.md
- configs/ReflexCtrlSaturn/README.md
- configs/ReflexCtrlVB/README.md
- configs/ReflexEncodeV1.2/README.md
- configs/ReflexEncodeV2.0/README.md
- www/README.md
Wrap bare URLs with angle brackets in Markdown files.
Rationale: Without angle brackets, a bare URL or email isn't converted into a link by some Markdown parsers.
https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md034---bare-url-used
> Fix bare URLs in Markdown files to ensure they are displayed properly

- headers/storagemanager.h
- proto/enums.proto
- src/configmanager.cpp
- src/configs/webconfig.cpp
- src/gamepad.cpp
- src/gp2040.cpp
- src/storagemanager.cpp
- www/src/Locales/en/SettingsPage.jsx
- www/src/Pages/SettingsPage.jsx
Details in  #1176, but saving to flash and host USB conflict, with the current code making the flash write safe but disabling interrupts on host USB's core for long enough to cause the connected dongle to disconnect. This makes most of the saves only occur if host USB is disabled (though they are still forced in the webconfig), and add a hotkey to force a save if you know what you're doing.
Resolves  #1176
> Restrict runtime saves

- CMakeLists.txt
- headers/addons/gamepad_usb_host.h
- headers/addons/gamepad_usb_host_listener.h
- proto/config.proto
- src/addons/gamepad_usb_host.cpp
- src/addons/gamepad_usb_host_listener.cpp
- src/config_utils.cpp
- src/configs/webconfig.cpp
- src/gp2040.cpp
- www/server/app.js
- www/src/Addons/GamepadUSBHost.tsx
- www/src/Pages/AddonsConfigPage.jsx
Previous PR #1102 by @smahdink
* Updates naming to GamepadUSB instead of Controller to avoid collision with controller objects.
* Adds secondary PID for DS4 usage.
* Fixes issue where GPIO-based inputs are overridden, preventing main GPIO controls from functioning.
* Cleans up white space usage for consistency
> Reimplementation of "ControllerHostAddon"

- src/display/ui/elements/GPLever.cpp
Optimizing Lever display logic for digital dpad
fixing bug for SOCD-N
> Optimizing Lever display for digital.

- headers/addons/gamepad_usb_host_listener.h
- src/addons/gamepad_usb_host_listener.cpp
This allows using the Ultrastick 360 to be used as an analog input by connecting it via the usb host port.
> Added support for the Ultimarc Ultrastik 360 to the gamepad plugin

- headers/gamepad.h
Very small PR to address #1248 
This allows SOCD none in the new USB HID mode.
> Update to allow the `SOCD none` mode in the new USB HID input mode

- www/src/Addons/SNES.tsx
As discussed on discord, this text was probably some remaining from the Wii Addon code that served as a base for the SNES Addon code, and Wii uses I2C (hence competing with Display) but SNES does not.
> Remove the note saying the SNES Addon is disabled when Display is in use

- .github/workflows/cmake.yml
- .github/workflows/node.js.yml
Updates the workflows to use a specific version runner images rather than the named "latest" to fix CI warnings
> Update GitHub Actions runners specifying ubuntu-latest

- www/src/Addons/Keyboard.tsx
- www/src/Components/ContextualHelpOverlay.tsx
- www/src/Components/KeyboardMapper.jsx
- www/src/Data/Buttons.js
- www/src/Locales/de-DE/Components.jsx
- www/src/Locales/en/Components.jsx
- www/src/Locales/ja-JP/Components.jsx
- www/src/Locales/ko-KR/Components.jsx
- www/src/Locales/pt-BR/Components.jsx
- www/src/Locales/zh-CN/Components.jsx
- www/src/Pages/PeripheralMappingPage.jsx
- www/src/Pages/SettingsPage.jsx
Also fixing a ton of type errors and remove unused code.
The validation for the keyboardMapper should no longer be necessary.
> Enables keyboard to use multiple of the same options across buttons

- headers/drivers/keyboard/KeyboardDriver.h
- proto/enums.proto
- src/addons/rotaryencoder.cpp
- src/drivers/keyboard/KeyboardDriver.cpp
- www/src/Addons/Rotary.tsx
- www/src/Locales/en/Addons/Rotary.jsx
Extended the rotary encoder to be used as a volume dial in the keyboard input driver.
This allows you to use the add-on Rotary Encoder, set your pins, and once in keyboard input mode it will up/down your volume.
> Keyboard Volume Dial - Rotary Encoder Extension

- www/src/Pages/SettingsPage.jsx
Validation for this until how/if we should handle different hotkeys with the same combination.
- Also aligns all the content in the rows vertically, some inputs where previously not centered
Could be better ways to do this, but could not think of any.
> Add validation for duplicate hotkey combinations

- .gitignore
- www/package-lock.json
- www/package.json
- www/tsconfig.json
- www/vite.config.ts
This exports enums from the protobuf definitions for use in development of the webconfig.  It will help reduce the need to reproduce these values in locations where they are listed, such as input modes or Display button layouts.
> Added process to export protobuf enums for use in webconfig

- CMakeLists.txt
the current regex to generate CMAKE_GIT_REPO_VERSION, which is especially touchy, expects git SHA lengths of exactly 7 characters. apparently the repo is big enough now that that's not enough, so git is returning SHAs of length 8, throwing off the regex
alternatively the regex could be updated to allow 7 or 8, but I hope we don't get to the point that two builds ever have the same 7-char SHA, let alone it being ambiguous what you are working with in that scenario
> apply --abbrev=7 to git describe, ignoring the birthday problem

- proto/enums.proto
- src/display/ui/elements/GPLever.cpp
Add options for GPLever button display object to invert directions for both X & Y in digital and analog modes.
Switched modes to use new GPLever_Mode enum.
> Digital/Analog Lever display options

- headers/drivers/ps4/PS4Descriptors.h
- src/addons/gamepad_usb_host_listener.cpp
Changed magic numbers for PS4 device IDs to use defines in Gamepad Host.
Added main PS4 "Console" IDs to Gamepad Host device check to allow both modes to function.
> Fixed PS4 mode support for Gamepad Host

- src/animationstation/animationstation.cpp
Brightness fix (was always setting animationOptions.brightness to 1 out of however many steps we got)
> Initial LED Brightness Fix

- src/addons/tilt.cpp
Disable Tilt functionality when addon is either disabled dynamically or pin mappings for percentage modifiers are unset.
> Disable Tilt if no pins mapped.

- headers/display/ui/screens/DisplaySaverScreen.h
- src/display/ui/screens/DisplaySaverScreen.cpp
Fixes the graphics for the toast and bounce images to use our gp2040-ce logo.
Slowed down toast so its not so chaotic.
> Fix for toast and bounce screen saver logos

- src/animationstation/effects/customthemepressed.cpp
- src/animationstation/effects/statictheme.cpp
Fixed missing custom theme pressed lights
I missed this when I was doing the LED overhaul
> Custom Theme Pressed Fix

- headers/drivers/ps4/PS4Driver.h
- src/drivers/ps4/PS4Driver.cpp
- src/storagemanager.cpp
Only do conditional saves if we're in PS4/PS5 usb dongle mode
> Update conditional saves to PS4/PS5 only

- www/src/Addons/SNES.tsx
- www/src/Addons/Wii.tsx
- www/src/Locales/de-DE/AddonsConfig.jsx
- www/src/Locales/en/Addons/WiiAddon.jsx
- www/src/Locales/en/AddonsConfig.jsx
- www/src/Locales/ja-JP/AddonsConfig.jsx
- www/src/Locales/ko-KR/AddonsConfig.jsx
- www/src/Locales/pt-BR/AddonsConfig.jsx
- www/src/Locales/zh-CN/AddonsConfig.jsx
This PR fixes https://github.com/OpenStickCommunity/GP2040-CE/issues/1362
1. HTML font size now in line with other add-ons
2. Fixed corresponding replacement tags in i18n files
3. Added missing first paragraph from the en i18n to SNES.tsx
4. Fixed a spelling inconsistency (also for Wii add-on which uses identical string)
5. Fixed some mistakes in the German SNES string
> Fix for wrong font size in SNES add-on configuration

- src/addons/gamepad_usb_host_listener.cpp
Some games require touchpad left and right clicks to fully function. I added the two extra buttons available, to be mapped to A3 and A4 in GP2040CE.
> Mapped Stadia Capture and Assistant button to touchpad right and left

- lib/PicoPeripherals/peripheral_usb.cpp
Setting state machine to regular pio_cfg now that we moved NeoPico to… pio1
This should fix pio_cfg since we've moved NeoPico over to the pio1
> TinyUSB State Machine - Back to Default

- headers/gamepad/GamepadState.h
- proto/enums.proto
- src/display/ui/elements/GPLever.cpp
- src/gamepad.cpp
my build has both a lever (dpad mode) and buttons assigned to direct digital, and a display that is intended to be input-pin-based rather than output-based (so that the same things display in the viewer regardless of which profile mode I am in). main works great for that, for buttons, but the current GP_LEVER_MODEs all are looking at the output, e.g. GP_LEVER_MODE_DIGITAL only shows the lever moving if the dpad is set to digital output, not e.g. left analog output. meanwhile, it would also show lever activity if I was pressing the direct digital buttons even when I wasn't moving the lever.
this fixes that by adding a new GP_LEVER_MODE_DPAD, which is looking at the unaltered dpad-mode input, regardless of how it is output, bringing the display lever functionally equivalent to GPIO-based …
> retain the unaltered DPAD state in order to use it in display

- lib/rndis/rndis.c
- src/drivers/net/NetDriver.cpp
- src/gp2040.cpp
Moving rndis init slightly and removing tusb_inint from the rndis driver and lib
This was an issue with tinyusb ports being wrong when rndis_init would call tusb_init(); (thank you Peter Harper!)
> Fix for rndis crashing the i2c

- headers/display/ui/screens/ButtonLayoutScreen.h
I realized a while back that I never did this and finally got back around to it. I feel like the button numbers are more useful for USBHID users than the old PS3-style PS coded buttons.
> code USBHID button display w/generic numbers rather than PS buttons

- .gitmodules
Hathach fixed the issues with USB enumeration on the rp2040. Moving TinyUSB and PICO-PIO back to the origin, confirmed working on all dongles I have.
> TinyUSB and Pico-PIO Revert for Enumeration Fix

- headers/addons/keyboard_host.h
- headers/addons/keyboard_host_listener.h
- proto/config.proto
- proto/enums.proto
- src/addons/keyboard_host_listener.cpp
- src/config_utils.cpp
- src/webconfig.cpp
- www/server/app.js
- www/src/Addons/Keyboard.tsx
- www/src/Locales/en/AddonsConfig.jsx
Keyboard host addon settings:
Example playing witcher on ps5:
https://github.com/user-attachments/assets/d89693fb-5c2d-4586-bda8-4d1339cfcbaa
> Allows mapping mouse to gamepad left/right stick

- CMakeLists.txt
- headers/display/GPGFX_UI_screens.h
- headers/display/ui/screens/NoUSBDetectedScreen.h
- src/addons/display.cpp
- src/display/ui/screens/NoUSBDetectedScreen.cpp
This PR adds a screen that will pop up if no USB data is detected.  This is used to help diagnose bad USB cables and ports.
> Add no USB Data detected screen
