lib/TinyUSB_Gamepad/src/hid_driver.cpp, platformio.ini
Hi!
This is a companion fix to be applied with https://github.com/OpenStickCommunity/MPG/pull/1
This fixes the call made in response to supply the magic bytes and also references latest MPG which is to be merged with aforementioned fix.
=> Fix PS button for PS3

headers/helper.h
Updating version for 0.6.0 release
=> Updating to 0.6.0 for new years release.

lib/AnimationStation/src/AnimationStation.cpp, lib/AnimationStation/src/Effects/Chase.hpp, lib/AnimationStation/src/Effects/Rainbow.hpp
Allows Debug build types to be built.
Please verify and merge.
Thank you.
=> Switch int values to proper absolute_time_t type

lib/FlashPROM/src/FlashPROM.cpp
Currently debug builds trigger multiple assertions in the Pi Pico SDK when `FlashPROM::commit()` is called.
This PR fixes thse issues:
`cancel_alarm(0)` will assert in `alarm_pool_cancel_alarm()` in `time.c`. I changed it so `cancel_alarm()` is only called when there actually is a pending alarm (`flashWriteAlarm != 0`).
Both `multicore_lockout_start_blocking()` and `multicore_lockout_end_blocking()` assert. Behind the scenes both functions actually use a timeout with a very large time constant (`0x7fffffffffffffff`). Unfortunately the time constant is so large that the subsequent calculations result in a `absolute_time_t` value outside of the allowed range, triggering the assert in `update_us_since_boot()`. I worked around this issue by using a smaller but still very long timeout (> …
=> Fixed multiple debug build issues in FlashPROM

configs/FightboardV3/BoardConfig.h, configs/FightboardV3Mirrored/BoardConfig.h
This fixes a build error caused by #56.
=> Updates Fightboard booardconfigs for #56

src/configs/webconfig.cpp
There were a bunch of issues with the implementation of LWIP callbacks in `webconfig.cpp`. This PR fixes the following issues:
- A `char*` of unknown lifetime was stored in `http_post_uri`. In the event of a multi-chunk POST request, the memory referenced by the pointer was invalid by the time the full request was received. Now a copy of the string is stored for later use.
- `httpd_post_receive_data()` can be called multiple times during a single POST request. The previous version did not handle this correctly, as a result only parts of the POST payload was retained.
- `httpd_post_finished()` was implemented incorrectly. Now the appropriate data is copied to `response_uri`. This also eliminates the need of the `is_post` flag and simplifies the `fs_open_custom()` function.
Also, I …
=> Fixed issues with multi-chunk POST requests

configs/WaveshareZero/BoardConfig.h
Very small update -- I noticed the pins in the config were switched from the asset.
Also some trimmed spaces hehe
=> Update Pins to match Pinout Asset

headers/storagemanager.h, src/addons/dualdirectional.cpp, src/storagemanager.cpp
Fixed dual directional so you can assign a single pin (such as just Up) as a dual directional input.
=> Fixed dual directional for single pin

.github/workflows/cmake.yml, CMakeLists.txt, lib/FlashPROM/src/FlashPROM.cpp
=> Pico sdk150

headers/addons/i2cdisplay.h, headers/storagemanager.h, src/addons/i2cdisplay.cpp, src/gp2040.cpp, src/storagemanager.cpp
I've attempted to address some problems with the said code and refactor accordingly.
With these changes, I'll also fix the default splash duration as per request soon.
Please review these changes, thanks!
=> Refactor and cleanup storagemanager and i2cdisplay (#120)

headers/addons/i2cdisplay.h, src/addons/i2cdisplay.cpp
=> Calculator mode

src/addons/reverse.cpp, src/addons/turbo.cpp, src/configs/webconfig.cpp
Fixed pin checks for Reverse and Turbo, as well as a Web Config pin c…heck that was missed.
Also decreased minimum Turbo shots from 5 to 2 (much slower).
=> Fixed pin checks which also fixes our input latency

configs/BentoBox/BoardConfig.h, configs/DURAL/BoardConfig.h, configs/FightboardV3/BoardConfig.h, configs/FightboardV3Mirrored/BoardConfig.h, configs/FlatboxRev4/BoardConfig.h, configs/FlatboxRev5/BoardConfig.h, configs/MavercadeKeebfighter/BoardConfig.h, configs/Pico/BoardConfig.h, configs/PicoAnn/BoardConfig.h, configs/PicoFightingBoard/BoardConfig.h, configs/SparkFunProMicro/BoardConfig.h, configs/WaveshareZero/BoardConfig.h
This adds some missing required information for the new Keyboard input type and hotkey actions configuration.
Please write if anything needs to be elaborated. Thank you.
=> Add keyboard and hotkey action BoardConfig doc

src/addons/analog.cpp
Stupid bug on my part, swapped analog pins. Also made it so you can run analog without setting the pins to match our other add-ons.
=> Super simple Analog fix

configs/BentoBox/BoardConfig.h, configs/DURAL/BoardConfig.h, configs/FightboardV3/BoardConfig.h, configs/FightboardV3Mirrored/BoardConfig.h, configs/FlatboxRev4/BoardConfig.h, configs/FlatboxRev5/BoardConfig.h, configs/MavercadeKeebfighter/BoardConfig.h, configs/Pico/BoardConfig.h, configs/PicoAnn/BoardConfig.h, configs/PicoFightingBoard/BoardConfig.h, configs/SparkFunProMicro/BoardConfig.h, configs/WaveshareZero/BoardConfig.h, headers/addons/slider_socd.h, headers/storagemanager.h, src/addons/slider_socd.cpp, src/configs/webconfig.cpp, src/storagemanager.cpp
Just like the hotkey update, this enables SOCD modes to be picked for the sliders.
=> Implement SOCD slider options

headers/helper.h
=> Preparing for 0.7.0 release

headers/helper.h, headers/storagemanager.h, src/addons/neopicoleds.cpp, src/addons/playerleds.cpp, src/storagemanager.cpp
Bug fix from PR https://github.com/OpenStickCommunity/GP2040-CE/pull/246
=> Fix PLED defines being used instead of new LEDOptions

www/src/Components/Navigation.js, www/src/Components/Navigation.scss
It looks like danger zone in the navbar was intended to be a button? This PR makes it so.
=> Make danger zone an actual button

.gitignore
These are a couple temporary files and directories that are made by using vim + YCM + clangd as an IDE.
=> .gitignore a couple files used by vim + tools

src/gamepad.cpp
Now that hotkeys are configurable it's possible to cause the hotkeys bound to `Up` or `Down` to flip if invert Y axis is enabled. This is a small change to move invert Y axis out of `Gamepad::read()` and into `Gamepad::process()` to avoid this issue.
=> Move invert Y to process() to avoid hotkey issues

headers/storagemanager.h, src/addons/neopicoleds.cpp, src/addons/playerleds.cpp, src/storagemanager.cpp
Fixes the flickering issue occurring in RC1.
=> Fixed PLEDs not being properly retrieved from protobuf

www/src/Pages/AddonsConfigPage.jsx
This solves the issue with not being to change the dual dir inputs with up/down buttons or setting it to "0"
=> Dual dir defaults

proto/config.proto
Reverts issue in a0c2d5d8ab35c6eafed39a491c3ea08088d02382. Hopefully not many people have that version serialized to a board.
=> unrenumber focusModeOptions

www/src/Components/KeyboardMapper.jsx, www/src/Locales/en/Components.jsx, www/src/Locales/en/KeyboardMapping.jsx, www/src/Pages/AddonsConfigPage.jsx, www/src/Pages/KeyboardMapping.jsx
Does what it says on the tin as well as correcting the tab spacing
=> Add missing translations for KeyboardMapper Component

src/gamepad.cpp
=> resolve #361

www/package-lock.json, www/package.json, www/src/Pages/AddonsConfigPage.jsx
Fix for the Web UI to accept PS4 keys again ('jsbn' broke in latest jsx changes)
=> PS4 Key Web-UI Fix

www/src/Components/Section.jsx, www/src/Components/Section.scss, www/src/Contexts/AppContext.jsx, www/src/Locales/en/Common.jsx, www/src/Pages/AddonsConfigPage.jsx, www/src/Pages/BackupPage.jsx, www/src/Pages/CustomThemePage.jsx, www/src/Pages/HomePage.jsx, www/src/Pages/KeyboardMapping.jsx, www/src/Pages/LEDConfigPage.jsx, www/src/Pages/PinMapping.jsx, www/src/Pages/SettingsPage.jsx, www/src/Services/WebApi.js
Adds a loading spinner to `Section`s when a `GET` is being performed and the data isn't ready yet.
=> Show a loading spinner when performing WebApi `GET`s

src/addons/board_led.cpp
fix for "Wrong LED order when inverting DPAD mode" https://github.com/OpenStickCommunity/GP2040-CE/issues/14
=> resolve issue 14

www/src/Locales/en/AddonsConfig.jsx, www/src/Pages/AddonsConfigPage.jsx
- Options for analog pins are now filtered by used pins
- Fixed some linting issues
- Added translation for "none"
=> Only show available analog pins on addons page

configs/FlatboxRev5RGB/env.ini
=> Fix env name for flatbox rev 5 rgb

www/src/Pages/AddonsConfigPage.jsx
=> Removing keyboard host add-on functionality from the web config

www/src/Pages/AddonsConfigPage.jsx
Looks like some -1 value sets snuck their way in.
Removing these to fix issue with assignment
=> Fixed tilt add-on pins for -1

headers/addons/jslider.h, src/addons/jslider.cpp
Modifying jslider to fix single-pin assignment issue.
=> JSlider single-pin fix

src/addons/keyboard_host.cpp
Will confirm this fixes the feather
=> Keyboard host IO flip for GPIO +5v en

src/addons/pspassthrough.cpp
Had the waiting for callback logic flipped, thanks jfedor!
=> PS add-on callback logic fix

www/src/Pages/SettingsPage.jsx
Changed number input to dropdown and added containers for toggle
Closes issue #506
=> fix: settings page layout (4-way joystick toggle, profile number)

docs/development.md
* Clean up whitespace/newlines
* Align headings so that two tab sets work in sync
=> Minor cleanup for development documentation

docs/app.js, docs/development.md, docs/index.html, docs/site.css, docs/web-configurator.md
Adds right-hand Table of Contents
Removes automatic H2, H3 hierarchy in left hand sidebar, only included H1 links.
Prevent ToC on devices smaller than 1300px wide
Miscellaneous corrections on web-configurator.md
=> Table of Contents

headers/gamepad/GamepadState.h
This is quick implementation which meet my expectation described in https://github.com/OpenStickCommunity/GP2040-CE/issues/532.
=> Another 4-Way Joystick Mode implementation

src/addons/input_macro.cpp
As discussed, this makes the Press type macro on positive input instead of the previous negative edge.
=> Switch Press macro type to positive edge

headers/addons/focus_mode.h, proto/config.proto, src/addons/input_macro.cpp, src/config_utils.cpp, src/configs/webconfig.cpp, www/server/app.js, www/src/Addons/FocusMode.tsx, www/src/Locales/en/Common.jsx
This implements a switch to lock the macro feature to the Focus Mode addon.
=> Add Macro Lock to Focus Mode addon

headers/addons/input_macro.h, proto/config.proto, src/configs/webconfig.cpp, www/src/Pages/InputMacroAddonPage.jsx
This PR makes small fixes to Macros as suggested.
Please review and merge, thank you!
=> Fix small issues with Macros

headers/addons/focus_mode.h, headers/addons/input_macro.h, proto/config.proto, src/addons/i2cdisplay.cpp, src/addons/input_macro.cpp, src/config_utils.cpp, src/configs/webconfig.cpp, www/server/app.js, www/src/Locales/en/InputMacroAddon.jsx, www/src/Pages/InputMacroAddonPage.jsx
This PR consists of additional requested Macro addon and related modifications.
=> More Macro fixes

src/addons/board_led.cpp, src/addons/keyboard_host.cpp, src/addons/snes_input.cpp, src/addons/tilt.cpp, src/addons/wiiext.cpp
We might think about a better way to do this in Gamepad, like "state->mid()" or something but for now this works great!
=> Updating All Gamepad MID Macros to use our mid-function

www/src/Components/CaptureButton.tsx, www/src/Locales/en/CaptureButton.jsx, www/src/Pages/InputMacroAddonPage.jsx
Fix for missing macro add-on button labels
=> Input Macro Add-on Button labels

www/package-lock.json, www/package.json, www/src/Addons/Ps4.tsx, www/src/Pages/LEDConfigPage.jsx
Only import SHA256 from crypto-js. (thanks for the tip @Pelsin !!)  Should reduce our webconfig by quite a bit
=> Only import SHA256 to decrease fsdata by ~50kb

site/docs/installation.mdx
In the Example Process, step 1 was duplicated.
=> Remove duplicative download instruction

src/configs/webconfig.cpp
Small fix for merge issues with the last two PRs
=> GPIO array merge fix

src/addons/keyboard_host.cpp, src/gamepad.cpp
Clean up some old code to get the hotkeys that were listed in issue 487 working correctly. Home was already working when I tested.
=> Fix issue 487

headers/gamepad/GamepadConfig.h, proto/config.proto, src/config_utils.cpp, src/configs/webconfig.cpp, src/gamepad.cpp, www/server/app.js, www/src/Pages/SettingsPage.jsx
Add more hotkeys as requested in issue 503.
=> add more hotkeys

www/src/Addons/Ps4.tsx
- The save message should not randomly disappear anymore
- Error/save message now resets after a new file is uploaded
- Should now only be possible to select one file per input
- Removed tons of lint errors
- The code is now formatted the same as the rest of the code base, hence the big change.
There are more things to improve, but this moves us a step forward.
=> Improve ps4 addon message handling

www/src/Addons/Ps4.tsx
Result and Hash have to be vars since they change
=> PS4 web fix

configs/FlatboxRev4/BoardConfig.h
This cleans up the base boardconfig.h for the Flatbox Rev4 to a minimal state.
I have added in the switch numbers that are originally referenced
=> Update to Flatbox Rev4 boardconfig.h

configs/Haute42/BoardConfig.h
The PR cleans up the Haute42 boardconfig
=> Update to Haute42 boardconfig.h

site/docs/usage.mdx
Changed hold shortcut for switching to Bootsel mode to the right button (S1 + P1 + P2)
=> Changed hold shortcut for switching to Bootsel mode to the right button (S1 + P1 + P2)

www/package-lock.json, www/package.json, www/server/app.js, www/src/Locales/en/LedConfig.jsx, www/src/Pages/LEDConfigPage.jsx
Restoring LED ordering in the LED config page
=> v0.7.6-RC2 Fix: Led reorder restore

src/gamepad.cpp
Counter increment was not rolling over correctly
=> v0.7.6-RC3 FIX: Hot-fix for counter increment

www/src/Locales/en/BackupPage.jsx, www/src/Locales/pt-BR/BackupPage.jsx, www/src/Locales/zh-CN/BackupPage.jsx, www/src/Pages/BackupPage.jsx
Suggestion to remove this as we might not be able to guarantee backwards compatibility.
=> Removing info section that we can use backups from different versions

CMakeLists.txt
Catch both hash values and hash values with a flag set such as -dirty
=> Regex Hash & Hash-Dirty 0.0.0 Replacement

configs/BentoBox/BoardConfig.h, configs/FightboardV3/BoardConfig.h, configs/FightboardV3Mirrored/BoardConfig.h, configs/FlatboxRev4/BoardConfig.h, configs/FlatboxRev5/BoardConfig.h, configs/FlatboxRev5RGB/BoardConfig.h, configs/FlatboxRev5Southpaw/BoardConfig.h, configs/Haute42/BoardConfig.h, configs/KB2040/BoardConfig.h, configs/KeyboardConverter/BoardConfig.h, configs/Liatris/BoardConfig.h, configs/OpenCore0/BoardConfig.h, configs/OpenCore0WASD/BoardConfig.h, configs/Pico/BoardConfig.h, configs/PicoFightingBoard/BoardConfig.h, configs/PicoW/BoardConfig.h, configs/RP2040AdvancedBreakoutBoard/BoardConfig.h, configs/RP2040AdvancedBreakoutBoardUSBPassthrough/BoardConfig.h, configs/RP2040MiniBreakoutBoard/BoardConfig.h, configs/RanaTadpole/BoardConfig.h, configs/ReflexCtrlSNES/BoardConfig.h, configs/ReflexEncodeV1.2/BoardConfig.h, configs/ReflexEncodeV2.0/BoardConfig.h, configs/SparkFunProMicro/BoardConfig.h, configs/Stress/BoardConfig.h, configs/WaveshareZero/BoardConfig.h
This PR removes all instances of defines in the boardconfig.h files that are already at the default value for that define.
=> Further cleanup of all boardconfig files

src/addons/i2cdisplay.cpp
This PR adds turbo rings to the fightboard right display
=> Add turbo rings for Fightboard right screen display

src/addons/turbo.cpp, src/config_utils.cpp
fixing the turbo available / update add-on pin
=> Turbo Available / update pin fix

.github/workflows/cmake.yml, .github/workflows/node.js.yml
Updated:
- actions/checkout
- actions/download-artifact
- actions/upload-artifact
- actions/setup-node
Tested this on a branch on my fork, still got some error referencing a old version, hence the WIP tag.
Unsure how to test it completely without having some changes in main as CMAKE workflow runs the node workflow.
=> WIP: Update worker deps for node 20

src/gp2040.cpp
Simple fix for boot action I messed up on input driver
=> Fix for X-Input Boot Action

src/configs/webconfig.cpp
=> unassign the old addon pin after assigning the new one

headers/display/ui/elements/GPScreen.h, headers/display/ui/screens/ButtonLayoutScreen.h, src/addons/display.cpp, src/display/ui/elements/GPScreen.cpp, src/display/ui/screens/ButtonLayoutScreen.cpp
* Fixes to displaying layout changes while in webconfig
* Added profile number banner display on profile change
* Updated some whitespace inconsistencies
=> Display updates for layout changes

src/config_utils.cpp
Also standardizes the profile naming scheme a bit for clarity.
Fixes #916.
=> Migrate the turbo pin to profiles, not just the core mappings

headers/addons/turbo.h, src/addons/turbo.cpp
=> recreate turboPinMask when doing reinit() (when profiles are changed)

lib/WiiExtension/extensions/ExtensionBase.cpp, lib/WiiExtension/extensions/NunchuckExtension.cpp
Some adjustments to the Wii calibration calculation to improve the analog range of movement.
=> Improvements to Wii calibration calculation

www/src/Components/CustomSelect.scss, www/src/Components/CustomSelect.tsx, www/src/Pages/PinMapping.tsx
=> Make pin mapping page easier on the eyes

www/README.md, www/package.json
Suggestion to use another bundle vizualiser without forcing devs to install it.
e.g
=> Change analyze command, dev dep. Update www readme

headers/addons/display.h, headers/display/ui/elements/GPScreen.h, headers/display/ui/screens/ButtonLayoutScreen.h, headers/display/ui/screens/ConfigScreen.h, headers/display/ui/screens/MainMenuScreen.h, headers/display/ui/screens/SplashScreen.h, src/addons/display.cpp, src/config_utils.cpp, src/display/ui/elements/GPScreen.cpp, src/display/ui/screens/ButtonLayoutScreen.cpp, src/display/ui/screens/ConfigScreen.cpp, src/display/ui/screens/MainMenuScreen.cpp, src/display/ui/screens/SplashScreen.cpp
This fixes macro upgrades and first-assignment getting messed up on protobuf checks.
PR#932
=> Macro and Display Fixes for RC1

src/addons/input_macro.cpp
This fixes the issues with macros repeating forever in exclusive mode.
This also fixes interrupt vs. exclusive for press and hold, toggle is a slightly weird beast but should work as intended.
=> Fixes for Macro interrupt & exclusive modes

lib/WiiExtension/extensions/GuitarExtension.cpp, src/display/ui/elements/GPButton.cpp, src/display/ui/elements/GPLever.cpp, src/display/ui/elements/GPShape.cpp
Wii
* Les Paul Wiitar calibration now allows full use of whammy bar
Display
* Elements on button layout screen now center horizontally when scaled down.
=> Additional I2C peripheral tweaks

www/src/Components/KeyboardMapper.jsx
=> Remove Fn from keyboardMapper

configs/BentoBox/BoardConfig.h, configs/FightboardV3/BoardConfig.h, configs/FightboardV3Mirrored/BoardConfig.h, configs/FlatboxRev5RGB/BoardConfig.h, configs/FlatboxRev5Southpaw/BoardConfig.h, configs/Granola/BoardConfig.h, configs/Haute42/BoardConfig.h, configs/KB2040/BoardConfig.h, configs/KeyboardConverter/BoardConfig.h, configs/Liatris/BoardConfig.h, configs/Mavercade/BoardConfig.h, configs/OpenCore0/BoardConfig.h, configs/OpenCore0WASD/BoardConfig.h, configs/Pico/BoardConfig.h, configs/PicoAnn/BoardConfig.h, configs/PicoFightingBoard/BoardConfig.h, configs/RP2040AdvancedBreakoutBoard/BoardConfig.h, configs/RP2040AdvancedBreakoutBoardUSBPassthrough/BoardConfig.h, configs/RP2040MiniBreakoutBoard/BoardConfig.h, configs/ReflexEncodeV1.2/BoardConfig.h, configs/ReflexEncodeV2.0/BoardConfig.h, configs/SGFBridget/BoardConfig.h, configs/SGFFaust/BoardConfig.h, configs/WaveshareZero/BoardConfig.h
Proposed config changes for BoardConfig.h to make addon mapping show up in web config for 0.7.8
=> BoardConfig Assigned_to_Addon Changes

configs/OpenCore0/BoardConfig.h
Didn't save locally so missed this one.
=> OpenCore0 addon pin removing extras

configs/Granola/BoardConfig.h, configs/Haute42/BoardConfig.h, configs/OpenCore0/BoardConfig.h, configs/OpenCore0WASD/BoardConfig.h, configs/RP2040AdvancedBreakoutBoardUSBPassthrough/BoardConfig.h, configs/ReflexEncodeV2.0/BoardConfig.h, configs/SGFFaust/BoardConfig.h
Missed second pin assignment for data line. Thanks speedypotato
=> Second pin assignment on data line assigned to addon

src/addons/input_macro.cpp
Single line fix for macro press. This was a fix for hold-repeat that messed up the press macro option.
=> Macro Press Fix

www/package-lock.json
Saw another PR that had package.lock diff without any changes in package.json, wanted to make sure it's correct and separate it in it's own PR
=> Update lock file

www/src/Pages/LEDConfigPage.jsx
This fixes an issue on the LED config page where after changing the order and saving, the Button Order list would revert to the initial page state. The save would still happen and the new order would show after a refresh, but was a bit confusing.
Also cleaned up a bit of the value conversions and centralized the data source creation for the draggable list.
=> Fix LED order reverting on save and cleanup

www/package-lock.json, www/package.json
=> Adding lodash types for IDEs that support TS intellisense

src/addons/keyboard_host.cpp, src/addons/keyboard_host_listener.cpp
Added ``setup()`` call for Keyboard Host listener on Keyboard Host ``setup()``
=> Keyboard Host fixes

www/src/Pages/PinMapping.tsx, www/src/Store/useProfilesStore.ts
=> Re-add the copy base profile functionality

src/drivers/xboxog/XboxOriginalDriver.cpp
Swap OG Xbox black/white button mappings. Fix for issue 1062.
=> fix issue 1062

www/src/Pages/SettingsPage.jsx
https://github.com/user-attachments/assets/825b1836-0ede-4e49-848c-f5ffa9036b7d
=> Add button to clear hotkey row

headers/addons/reactiveleds.h, proto/config.proto, src/addons/reactiveleds.cpp, src/configs/webconfig.cpp, www/server/app.js
Fixed issue with reactive LEDs not using all configurable LEDs.
Added 2 extra LED slots bringing the count to 10.
=> Reactive LED fixes

www/src/Addons/Turbo.tsx, www/src/Locales/en/PinMapping.jsx
Validation same as TURBO_SHOT_MIN in https://github.com/OpenStickCommunity/GP2040-CE/blob/main/src/addons/turbo.cpp#L12
=> Minor fixes

src/drivers/keyboard/KeyboardDriver.cpp
We added A3 and A4 assignment, but need to add it to the Keyboard Driver
=> Keyboard Driver - A3/A4 Fix

src/drivermanager.cpp, src/drivers/xinput/XInputDriver.cpp, src/gp2040.cpp, src/gp2040aux.cpp, src/main.cpp, src/usbhostmanager.cpp
Fix for when descriptor is called repeatedly for xbox 360
=> Xbox 360 Fix

headers/addons/analog.h, src/addons/analog.cpp, src/drivers/switch/SwitchDriver.cpp
Lots of cleanups in analog, fixed center based on mid-point of driver (0x8000 or 0x7FFF)
=> Analog Clean-up and Center Fix for All Drivers

headers/drivers/xbone/XBOneDescriptors.h, headers/drivers/xbone/XBOneDriver.h, src/addons/neopicoleds.cpp, src/drivers/xbone/XBOneAuthUSBListener.cpp, src/drivers/xbone/XBOneDriver.cpp
Add player LED support for Xbox One
=> Player LED - Xbox One

www/src/Contexts/AppContext.jsx, www/src/Pages/DisplayConfig.jsx, www/src/Pages/SettingsPage.jsx
Combining two useEffects in our settings page to hopefully offset timings
=> RC2 WWW timing fix

www/src/Locales/ja-JP/SettingsPage.jsx
fixed the string translation to be in-line with the fix at #1162
=> update ja-JP locale XInput string inline with en string update

headers/addons/keyboard_host_listener.h, src/addons/keyboard_host_listener.cpp
Small bits of clean-up to keyboard host. Should guarantee dev addr, instance, protocol type, mount/unmounts, and update loops
=> Keyboard Host Clean-up / Unmount Bug Fix

.github/workflows/cmake.yml, .gitignore, CMakeLists.txt, lib/NeoPico/src/generated/ws2812.pio.h, pico_sdk_import.cmake
Reverts OpenStickCommunity/GP2040-CE#1179
Breaking changes in pico sdk is going to keep us on 1.5 for a bit
=> Revert "Updating pico build version"

src/gp2040aux.cpp
Add rumble and reactive LEDs back in, I missed these on my modifications for Xbox 360 auth support
=> Regression fix (thank you BRP)

headers/gamepad/GamepadState.h
Update GamepadState.h with directions to use Function on custom hotkeys.
=> Update GamepadState.h with directions to use Function on custom hotkeys

.github/workflows/cmake.yml
=> CMake Fix for Github breakage

headers/gp2040.h, src/addons/neopicoleds.cpp, src/addons/turbo.cpp, src/animationstation/animationstation.cpp, src/gp2040.cpp
Fix for forceSave on events working in gp2040.cpp
=> Force-Save Fix for GP2040 Events

www/src/Locales/en/InputMacroAddon.jsx, www/src/Pages/InputMacroAddonPage.tsx
Also added some validations if one where to import more than maximum inputs / incorrect types
https://github.com/user-attachments/assets/725cb53b-7ee5-46ce-bdff-fffc70e81e43
=> Adds an advanced tab where individual macro definitions as json can be copied/import

src/display/ui/screens/MainMenuScreen.cpp
Only show profiles under the Main Menu profile menu screen that are e…nabled (or profile #1)
=> Profile Mini Menu Fix

headers/storagemanager.h, lib/rndis/rndis.c, src/addons/display.cpp, src/display/GPGFX_UI.cpp, src/webconfig.cpp, www/src/Locales/en/DisplayConfig.jsx
Removing redundant previewDisplayOptions
Updated Screen Saver 0 for OFF (English only for now)
=> Button Layout Preview Fix for Web-Config

src/storagemanager.cpp
Update force save to a conditional based on input driver (and xb360 auth mode present)
=> Force Save Conditionals Update

www/server/app.js, www/src/Locales/en/PinMapping.jsx, www/src/Pages/PinMapping.tsx, www/src/Pages/SettingsPage.jsx
Should resolve: https://github.com/OpenStickCommunity/GP2040-CE/issues/1172
=> Disallow disabling of active profile and choosing a disabled profile in gamepad settings

www/src/Addons/Analog.tsx, www/src/Addons/Analog1256.tsx, www/src/Addons/Bootsel.tsx, www/src/Addons/Buzzer.tsx, www/src/Addons/DRV8833.tsx, www/src/Addons/DualDirection.tsx, www/src/Addons/FocusMode.tsx, www/src/Addons/GamepadUSBHost.tsx, www/src/Addons/I2CAnalog1219.tsx, www/src/Addons/Keyboard.tsx, www/src/Addons/OnBoardLed.tsx, www/src/Addons/PCF8575.tsx, www/src/Addons/ReactiveLED.tsx, www/src/Addons/Reverse.tsx, www/src/Addons/Rotary.tsx, www/src/Addons/SNES.tsx, www/src/Addons/SOCD.tsx, www/src/Addons/Tilt.tsx, www/src/Addons/Turbo.tsx, www/src/Addons/Wii.tsx, www/src/Locales/en/AddonsConfig.jsx
Link the titles to docs, add alerts, fix wording, link GPIO and Peripheral mapping within alerts
=> Add-on cleaning

.github/workflows/cmake.yml
When selecting a configs it should skip the others, should drastically reduce the build time when only building one config
=> Add option to select what config to build from github actions

.gitmodules
@Pelsin thank you for finding my missing submodule ref.
Moving over to our local tinyusb/pico-pio so we can modify as needed
=> Moving to OpenStickCommunity TinyUSB/Pico-PIO

src/webconfig.cpp
Tested on:
- PicoW, check that they arent triggered automatically
- Haute42 s13, check that they arent triggered automatically
- RP2040 Advanced Breakout Board, manually triggering 23
Resolves https://github.com/OpenStickCommunity/GP2040-CE/issues/871
=> Fixes issue with getHeldPins on 23,24,25,29
